exports.trans = {
    "Encrypt": {
        "en": "Encryption of all passwords done!",
        "de": "Verschlüsselung aller Passwörter!",
        "ru": "Шифрование всех паролей!",
        "pt": "Criptografia de todas as senhas feitas!",
        "nl": "Encryptie van alle wachtwoorden!",
        "fr": "Cryptage de tous les mots de passe !",
        "it": "Crittografia di tutte le password fatte!",
        "es": "¡Encriptación de todas las contraseñas hechas!",
        "pl": "Wszystko o wszystkich hasłach zrobiono!",
        "uk": "Зашифрування всіх паролів зроблено!",
        "zh-cn": "摘录所有密码!"
    },
    "Device_disabled": {
        "en": "Device %s is disabled.",
        "de": "Gerät %s ist deaktiviert.",
        "ru": "Устройства %s отключены.",
        "pt": "O dispositivo %s está desativado.",
        "nl": "Device %s is gehandicapt.",
        "fr": "Le dispositif %s est désactivé.",
        "it": "Il dispositivo %s è disattivato.",
        "es": "El dispositivo %s está deshabilitado.",
        "pl": "Device %s jest niepełnosprawne.",
        "uk": "Пристрої %s вимкнено.",
        "zh-cn": "Device %s残疾。."
    },
    "Language": {
        "en": "Language: %s",
        "de": "Sprache: %s",
        "ru": "Язык: %s",
        "pt": "Língua: %s",
        "nl": "Taal: %s",
        "fr": "Langue: %s",
        "it": "Lingua: %s",
        "es": "Idioma: %s",
        "pl": "Język: %s",
        "uk": "Мова: %s",
        "zh-cn": "语文: %s"
    },
    "DeviceID": {
        "en": "Device ID: %s",
        "de": "Geräte-ID: %s",
        "ru": "ID устройства: %s",
        "pt": "ID do dispositivo: %s",
        "nl": "Device ID: %s",
        "fr": "ID du dispositif: %s",
        "it": "ID dispositivo: %s",
        "es": "ID del dispositivo: %s",
        "pl": "Device ID: %s",
        "uk": "Ідентифікатор пристрою: %s",
        "zh-cn": "Device ID: %s"
    },
    "Please enter an IP": {
        "en": "Please enter an IP.",
        "de": "Bitte geben Sie eine IP ein.",
        "ru": "Пожалуйста, введите IP.",
        "pt": "Por favor, insira um IP.",
        "nl": "Betrek alsjeblieft een IP.",
        "fr": "Veuillez entrer une IP.",
        "it": "Si prega di inserire un IP.",
        "es": "Por favor, introduzca una IP.",
        "pl": "Wstęp do IP.",
        "uk": "Введіть номер мобільного, який Ви вказали при укладаннi договору з банком - для ідентифікації.",
        "zh-cn": "请加入IP。."
    },
    "Port default": {
        "en": "No Port specified! Port default set to 80.",
        "de": "Kein Port angegeben! Port Standard auf 80 gesetzt.",
        "ru": "Порт не указан! Порт по умолчанию установлен до 80.",
        "pt": "Nenhuma porta especificada! Porta padrão definido para 80.",
        "nl": "Geen Port gespecificeerd! Portafwijking gestart tot 80.",
        "fr": "Pas de port spécifié ! Port default set to 80.",
        "it": "Nessuna porta specificata! Impostazione predefinita della porta a 80.",
        "es": "¡No hay Puerto especificado! Port default set to 80.",
        "pl": "Port nie został określony. Port domyślny plan to 80 lat.",
        "uk": "Ні Порт вказаний! Портовий за замовчуванням встановлюється до 80.",
        "zh-cn": "无港口规定! 第80条."
    },
    "USED_Username": {
        "en": "Username and password are used for device %s.",
        "de": "Benutzername und Passwort werden für das Gerät %s verwendet.",
        "ru": "Имя пользователя и пароль используются для устройства %s.",
        "pt": "Nome de usuário e senha são usados para dispositivo %s.",
        "nl": "Noem en wachtwoord worden gebruikt voor apparaat %s.",
        "fr": "Nom d'utilisateur et mot de passe sont utilisés pour le dispositif %s.",
        "it": "Nome utente e password sono utilizzati per il dispositivo %s.",
        "es": "Nombre de usuario y contraseña se utilizan para el dispositivo %s.",
        "pl": "Użytkowniki i hasła są używane do urządzenia %s.",
        "uk": "Ім'я та пароль використовуються для пристрою %s.",
        "zh-cn": "用于装置%s。."
    },
    "Offline": {
        "en": "Device %s starts offline...",
        "de": "Gerät %s startet offline.",
        "ru": "Устройство %s начинает офлайн.",
        "pt": "O dispositivo %s começa offline.",
        "nl": "Device %s begint offline.",
        "fr": "L'appareil %s commence hors ligne.",
        "it": "Il dispositivo %s inizia offline.",
        "es": "El dispositivo %s comienza fuera de línea.",
        "pl": "Uwaga %s rozpoczyna się od linii.",
        "uk": "Пристрої %s стартують в автономному режимі.",
        "zh-cn": "%s名司机开除。."
    },
    "Standby_Modus": {
        "en": "The device %s starts in standby modus...",
        "de": "Das Gerät %s startet im Standby-Modus.",
        "ru": "Устройство %s начинается в режиме ожидания.",
        "pt": "O dispositivo %s começa no modus standby.",
        "nl": "Het apparaat %s begint in stand-by modus.",
        "fr": "L'appareil %s commence par modus standby.",
        "it": "Il dispositivo %s inizia in modalità standby.",
        "es": "El dispositivo %s comienza en modo de espera.",
        "pl": "Urządzenie %s rozpoczyna się w trybie standby.",
        "uk": "Пристрій %s починається в режимі очікування.",
        "zh-cn": "装置%s在待命单元中开始。."
    },
    "Unreachable": {
        "en": "Your device with IP %s:%s is unreachable. Please check your Instance configuration and restart your adapter.",
        "de": "Ihr Gerät mit IP %s:%s ist nicht erreichbar. Bitte überprüfen Sie Ihre Instanz-Konfiguration und starten Sie Ihren Adapter neu.",
        "ru": "Ваше устройство с IP %s:%s недоступно. Пожалуйста, проверьте настройки и перезагрузите адаптер.",
        "pt": "Seu dispositivo com IP %s:%s não é possível. Verifique sua configuração de instância e reinicie seu adaptador.",
        "nl": "Je apparaat met IP %s:%s is onbereikbaar. Controleer uw instance configuratie en herstel uw adapter.",
        "fr": "Votre appareil avec IP %s:%s est inaccessible. Veuillez vérifier la configuration de votre instance et redémarrer votre adaptateur.",
        "it": "Il tuo dispositivo con IP %s:%s è irraggiungibile. Si prega di controllare la configurazione del vostro caso e riavviare il vostro adattatore.",
        "es": "Su dispositivo con IP %s:%s es inalcanzable. Por favor, compruebe su configuración de Instance y reinicie su adaptador.",
        "pl": "Urządzenie z IP %s:%s nie jest dozwolone. Poświadczasz swoją konfigurację i odwracaj swojego adaptera.",
        "uk": "Ваш пристрій з IP %s:%s ненадійна. Будь ласка, перевірте налаштування та перезапустіть адаптер.",
        "zh-cn": "你有IP%s的装置:其%s是无法实现的。 请检查你的配置,并重新安排你们的适应者。."
    },
    "Connection": {
        "en": "Connection to %s device failed.",
        "de": "Verbindung zu %s Gerät gescheitert.",
        "ru": "Подключение к %s устройству не удалось.",
        "pt": "A conexão com %s dispositivo falhou.",
        "nl": "Verbinding met een apparaat faalde.",
        "fr": "La connexion à %s appareil a échoué.",
        "it": "La connessione a %s dispositivo non è riuscita.",
        "es": "La conexión a %s dispositivo falló.",
        "pl": "Połączenie do %s urządzenia nie powiodło się.",
        "uk": "Підключення до %s пристрою не вдалося.",
        "zh-cn": "对%s个装置的控制失败。."
    },
    "DEVICEINFO": {
        "en": "DEVICEINFO created for device %s.",
        "de": "DEVICEINFO erstellt für das Gerät %s.",
        "ru": "ДевайсИнфо создан для устройства %s.",
        "pt": "DESENVOLVIMENTO criado para o dispositivo %s.",
        "nl": "DEVICEINFO Gemaakt voor apparaat %s.",
        "fr": "DEVICEINFO créé pour le dispositif %s.",
        "it": "DISPONIBILE creato per dispositivo %s.",
        "es": "DEVICEINFO creado para el dispositivo %s.",
        "pl": "DEVICEN Zaprojektowany dla urządzenia %s.",
        "uk": "ДЕВИТІНФО створений для пристрою %s.",
        "zh-cn": "DEVICEINFO 制造装置%s。."
    },
    "Remote_Folder": {
        "en": "Remote Folder created for device %s.",
        "de": "Remote Folder erstellt für Gerät %s.",
        "ru": "Remote Folder создан для устройства %s.",
        "pt": "Pasta remota criada para dispositivo %s.",
        "nl": "Verwijder Folder gemaakt voor apparaat %s.",
        "fr": "Dossier distant créé pour le périphérique %s.",
        "it": "Cartella remota creata per il dispositivo %s.",
        "es": "Carpeta remota creada para el dispositivo %s.",
        "pl": "Remote Folder stworzył dla urządzenia %s.",
        "uk": "Віддалений складник, створений для пристрою %s.",
        "zh-cn": "用于装置第%s号的遥控器。."
    },
    "Determine": {
        "en": "Cannot determine the status of device %s.",
        "de": "Kann den Status des Geräts %s nicht bestimmen.",
        "ru": "Не можете определить статус устройства %s.",
        "pt": "Não é possível determinar o estado do dispositivo %s.",
        "nl": "Kan de status van apparaat %s niet bepalen.",
        "fr": "Ne peut pas déterminer l'état du dispositif %s.",
        "it": "Non è possibile determinare lo stato del dispositivo %s.",
        "es": "No se puede determinar el estado del dispositivo %s.",
        "pl": "Cannot określa status urządzenia %s.",
        "uk": "Не можна визначити стан пристрою %s.",
        "zh-cn": "评 注%s."
    },
    "TunerInfos": {
        "en": "TunerInfos created for device %s.",
        "de": "TunerInfos erstellt für Gerät %s.",
        "ru": "TunerInfos создан для устройства %s.",
        "pt": "TunerInfos criado para dispositivo %s.",
        "nl": "TunerInfos gemaakt voor apparaat %s.",
        "fr": "TunerInfos créées pour le dispositif %s.",
        "it": "TunerInfos creato per dispositivo %s.",
        "es": "TunerInfos creado para el dispositivo %s.",
        "pl": "TunerInfos stworzył dla urządzenia %s.",
        "uk": "TunerInfos створений для пристрою %s.",
        "zh-cn": "用于装置的图里信息系统 %s."
    },
    "StatusInfos": {
        "en": "StatusInfos created for device %s.",
        "de": "StatusInfos erstellt für Gerät %s.",
        "ru": "StatusInfos создан для устройства %s.",
        "pt": "StatusInfos criado para dispositivo %s.",
        "nl": "StatusInfos gemaakt voor apparaat %s.",
        "fr": "StatusInfos créées pour le périphérique %s.",
        "it": "StatusInfos creato per il dispositivo %s.",
        "es": "StatusInfos creado para el dispositivo %s.",
        "pl": "StatusInfos stworzył dla urządzenia %s.",
        "uk": "СтатусІнфос створений для пристрою %s.",
        "zh-cn": "用于装置的现况信息第%s号。."
    },
    "Cannot_Bouquets": {
        "en": "Cannot find any Bouquets from device %s.",
        "de": "Kann keine Bouquets vom Gerät %s finden.",
        "ru": "Не можете найти любые Букеты с устройства %s.",
        "pt": "Não é possível encontrar nenhum Bouquets do dispositivo %s.",
        "nl": "Kan geen Bouquets vinden van apparaat %s.",
        "fr": "Ne trouvez pas de Bouquets de l'appareil %s.",
        "it": "Non è possibile trovare alcun Bouquets dal dispositivo %s.",
        "es": "No se pueden encontrar Bouquets desde el dispositivo %s.",
        "pl": "Cannot odnalazł urządzenie %s.",
        "uk": "Не можна знайти будь-які Букети з пристрою %s.",
        "zh-cn": "未发现任何布克从装置第%s号。."
    },
    "Bouquets_and_EPG": {
        "en": "Bouquets and EPG created for device  %s.",
        "de": "Bouquets und EPG erstellt für Gerät %s.",
        "ru": "Букеты и EPG созданы для устройства %s.",
        "pt": "Bouquets e EPG criados para dispositivo %s.",
        "nl": "Bouquets en EPG gemaakt voor apparaat %s.",
        "fr": "Bouquets et EPG créés pour le dispositif %s.",
        "it": "Bouquets e EPG creati per il dispositivo %s.",
        "es": "Bouquets y EPG creados para el dispositivo %s.",
        "pl": "Bouquets and EPG – stworzone dla urządzenia %s.",
        "uk": "Букети і ЕПГ створюються для пристрою %s.",
        "zh-cn": "用于装置第%s号。."
    },
    "Starts_Interval": {
        "en": "Device %s starts with an interval of %s seconds.",
        "de": "Gerät %s beginnt mit einem Intervall von %s Sekunden.",
        "ru": "Устройство %s начинается с интервала %s секунд.",
        "pt": "O dispositivo %s começa com um intervalo de %s segundos.",
        "nl": "Device %s begint met een interval van %s seconden.",
        "fr": "Le périphérique %s commence par un intervalle de %s secondes.",
        "it": "Il dispositivo %s inizia con un intervallo di %s secondi.",
        "es": "El dispositivo %s comienza con un intervalo de %s segundos.",
        "pl": "Device %s rozpoczyna się od przedziału %s sekund.",
        "uk": "Пристрої %s починаються з інтервалом %s секунд.",
        "zh-cn": "%s 证人开始%s秒。."
    },
    "All_Datapoints": {
        "en": "All Datapoints: %s.",
        "de": "Alle Datapoints: %s.",
        "ru": "Все данные: %s.",
        "pt": "Todos os Datapoints: %s.",
        "nl": "Alle Datapoints: %s.",
        "fr": "Tous les points de données: %s.",
        "it": "Tutti i Datapoint: %s.",
        "es": "All Datapoints: %s.",
        "pl": "Wszystkie dane: %s.",
        "uk": "Усі точки даних: %s.",
        "zh-cn": "所有数据点:%s."
    },
    "Deleted": {
        "en": "Deleted: %s.",
        "de": "Gelöscht: %s.",
        "ru": "Удален: %s.",
        "pt": "Excluído: %s.",
        "nl": "Gewist: %s.",
        "fr": "Deleted: %s.",
        "it": "Cancellato: %s.",
        "es": "Suprimido: %s.",
        "pl": "W: %s.",
        "uk": "Видалення: %s.",
        "zh-cn": "删除:%s."
    },
    "Interval_Recording": {
        "en": "Interval Recording starts for %s.",
        "de": "Interval Recording beginnt für %s.",
        "ru": "Интервал запись начинается на %s.",
        "pt": "Registro de Intervalo começa para %s.",
        "nl": "Interval Recording begint voor %s.",
        "fr": "L'enregistrement intervale commence pour %s.",
        "it": "Interval Recording inizia per %s.",
        "es": "Interval Recording comienza por %s.",
        "pl": "Interval Recording rozpoczyna się od %s.",
        "uk": "Interval Запис починається на %s.",
        "zh-cn": "B. 汇率记录开始为%s个."
    },
    "Start_recording_interval": {
        "en": "Start recording interval for %s.",
        "de": "Aufnahmeintervall für %s starten.",
        "ru": "Запуск интервала записи для %s.",
        "pt": "Comece o intervalo de gravação para %s.",
        "nl": "Begin de interval op te nemen voor %s.",
        "fr": "Commencez l'intervalle d'enregistrement pour %s.",
        "it": "Avviare l'intervallo di registrazione per %s.",
        "es": "Comience el intervalo de grabación para %s.",
        "pl": "Odcinek %s.",
        "uk": "Почати інтервал запису для %s.",
        "zh-cn": "B. 开始记录%s年的间隔."
    },
    "Starting_checking_recordings": {
        "en": "Starting checking the recordings for device %s.",
        "de": "Beginn der Überprüfung der Aufnahmen für das Gerät %s.",
        "ru": "Начало проверки записей для устройства %s.",
        "pt": "Iniciando a verificação das gravações para o dispositivo %s.",
        "nl": "Begin de opnames te controleren voor apparaat %s.",
        "fr": "En commençant à vérifier les enregistrements du périphérique %s.",
        "it": "Controllo delle registrazioni per il dispositivo %s.",
        "es": "Comienza a revisar las grabaciones para el dispositivo %s.",
        "pl": "Zaczyna sprawdzać nagrania dla urządzenia %s.",
        "uk": "Почати перевірку записів для пристрою %s.",
        "zh-cn": "B. 开始检查装置的录音记录 %s."
    },
    "Checking_DeepStandby": {
        "en": "Checking DeepStandby from device %s.",
        "de": "Prüfen von DeepStandby vom Gerät %s.",
        "ru": "Проверка DeepStandby с устройства %s.",
        "pt": "Verificando DeepStandby do dispositivo %s.",
        "nl": "Controleer DeepStandby van apparaat %s.",
        "fr": "Vérification de DeepStandby depuis le périphérique %s.",
        "it": "Controllo DeepStandby dal dispositivo %s.",
        "es": "Revisando DeepStandby desde el dispositivo %s.",
        "pl": "Checking DeepStandby z urządzenia %s.",
        "uk": "Перевірити DeepStandby від пристрою %s.",
        "zh-cn": "B. 从装置中查验深装置 %s."
    },
    "Connected_device": {
        "en": "Connected with device %s.",
        "de": "Mit dem Gerät %s verbunden.",
        "ru": "Подключен с устройством %s.",
        "pt": "Conectado com dispositivo %s.",
        "nl": "Geconnecteerd met apparaat %s.",
        "fr": "Connecté avec le dispositif %s.",
        "it": "Collegato con dispositivo %s.",
        "es": "Conectado con el dispositivo %s.",
        "pl": "Połączenie z urządzeniem %s.",
        "uk": "З'єднання з пристроєм %s.",
        "zh-cn": "A. 与装置的接触 %s."
    },
    "Device_disconnected": {
        "en": "Device %s disconnected.",
        "de": "Gerät %s getrennt.",
        "ru": "Устройство %s отключено.",
        "pt": "Dispositivo %s desligado.",
        "nl": "Vernietiging %s.",
        "fr": "Appareil %s déconnecté.",
        "it": "Dispositivo %s scollegato.",
        "es": "Dispositivo %s desconectado.",
        "pl": "Zbiór %s.",
        "uk": "Пристрої %s відключені.",
        "zh-cn": "Device %s脱钩。."
    },
    "Device_offline": {
        "en": "Device %s is offline.",
        "de": "Gerät %s ist offline.",
        "ru": "Устройство %s оффлайн.",
        "pt": "O dispositivo %s está offline.",
        "nl": "Device %s is offline.",
        "fr": "L'appareil %s est hors ligne.",
        "it": "Il dispositivo %s è offline.",
        "es": "El dispositivo %s está fuera de línea.",
        "pl": "Uwaga %s.",
        "uk": "Пристрої %s офлайн.",
        "zh-cn": "Device %s号不线。."
    },
    "reject_device": {
        "en": "reject: %s device: %s",
        "de": "Ablehnung: %s Gerät: %s",
        "ru": "отказ: %s устройство: %s",
        "pt": "rejeitar: %s dispositivo: %s",
        "nl": "afwijzing: %s apparaat: %s",
        "fr": "rejet: %s appareil: %s",
        "it": "rifiuto: %s dispositivo: %s",
        "es": "rechazar: %s dispositivo: %s",
        "pl": "odrzucenie: %s urządzenie: %s",
        "uk": "відхилення: %s пристрій: %s",
        "zh-cn": "反对:%s装置:%s"
    },
    "Used_HTTPS": {
        "en": "Used HTTPS for device %s.",
        "de": "Gebrauchte HTTPS für Gerät %s.",
        "ru": "Используется HTTPS для устройства %s.",
        "pt": "HTTPS usado para dispositivo %s.",
        "nl": "Gebruikte HTPS voor apparaat %s.",
        "fr": "HTTPS utilisé pour le périphérique %s.",
        "it": "HTTPS usato per il dispositivo %s.",
        "es": "HTTPS usado para el dispositivo %s.",
        "pl": "Zastosowanie protokołu %s.",
        "uk": "Використовується HTTPS для пристрою %s.",
        "zh-cn": "使用HTTPS进行装置%s."
    },
    "Start Update for device": {
        "en": "Start Update for device %s.",
        "de": "Start Update für das Gerät %s.",
        "ru": "Start Update для устройства %s.",
        "pt": "Iniciar atualização para dispositivo %s.",
        "nl": "Start Update voor apparaat %s.",
        "fr": "Mettre à jour le dispositif %s.",
        "it": "Avviare l'aggiornamento per il dispositivo %s.",
        "es": "Iniciar actualización para el dispositivo %s.",
        "pl": "Uruchomienie urządzenia %s.",
        "uk": "Почати оновлення для пристрою %s.",
        "zh-cn": "B. 装置的最新情况 %s."
    },
    "In process": {
        "en": "In process: %s",
        "de": "Im Prozess: %s",
        "ru": "В процессе: %s",
        "pt": "Em processo: %s",
        "nl": "In het proces: %s",
        "fr": "En cours: %s",
        "it": "In processo: %s",
        "es": "En proceso: %s",
        "pl": "Proces: %s",
        "uk": "В процесі: %s",
        "zh-cn": "进程: %s"
    },
    "INFO powerstate": {
        "en": "INFO powerstate: %s",
        "de": "INFO Powerstate: %s",
        "ru": "Powerstate ИНФО: %s",
        "pt": "INFO powerstate: %s",
        "nl": "INFO powerstate: %s",
        "fr": "INFO powerstate: %s",
        "it": "Stato di potere INFO: %s",
        "es": "INFO powerstate: %s",
        "pl": "INFO powerstate: %s",
        "uk": "ІНФО потужністьдержава: %s",
        "zh-cn": "电力公司: %s"
    },
    "Device_standby": {
        "en": "Device %s is in standby.",
        "de": "Das Gerät %s ist im Standby.",
        "ru": "Устройство %s находится в режиме ожидания.",
        "pt": "O dispositivo %s está em espera.",
        "nl": "Device %s is stand-by.",
        "fr": "L'appareil %s est en attente.",
        "it": "Il dispositivo %s è in standby.",
        "es": "El dispositivo %s está en espera.",
        "pl": "Uwaga %s znajduje się w rękach.",
        "uk": "Пристрої %s в режимі очікування.",
        "zh-cn": "%s人待命。."
    },
    "Device_online": {
        "en": "Device %s is online.",
        "de": "Gerät %s ist online.",
        "ru": "Устройство %s онлайн.",
        "pt": "O dispositivo %s está online.",
        "nl": "Device %s is online.",
        "fr": "L'appareil %s est en ligne.",
        "it": "Il dispositivo %s è online.",
        "es": "El dispositivo %s está en línea.",
        "pl": "Device %s jest online.",
        "uk": "Пристрої %s онлайн.",
        "zh-cn": "%s 证人在线。."
    },
    "New interval Online": {
        "en": "Device %s is online. New interval for device %s is set.",
        "de": "Gerät %s ist online. Ein neuer Intervall für das Gerät %s wird eingestellt.",
        "ru": "Устройство %s онлайн. Установлен новый интервал для устройства %s.",
        "pt": "O dispositivo %s está online. Novo intervalo para o dispositivo %s é definido.",
        "nl": "Device %s is online. Nieuwe interval voor apparaat %s is klaar.",
        "fr": "Appareil %s est en ligne. Un nouvel intervalle pour le dispositif %s est défini.",
        "it": "Il dispositivo %s è online. Viene impostato un nuovo intervallo per il dispositivo %s.",
        "es": "El dispositivo %s está en línea. Se establece un nuevo intervalo para el dispositivo %s.",
        "pl": "Device %s jest online. Uruchomiono nowe przedziały dla urządzenia %s.",
        "uk": "Пристрої %s онлайн. Новий інтервал для пристрою %s встановлюється.",
        "zh-cn": "Device %s 在线。 安装了用于装置%s的新间隔。."
    },
    "find_info_device": {
        "en": "Can't find any info from device %s.",
        "de": "Kann keine Informationen von device %s finden.",
        "ru": "Не можете найти информацию с устройства %s.",
        "pt": "Não consigo encontrar nenhuma informação do dispositivo %s.",
        "nl": "Ik kan geen informatie vinden van apparaat %s.",
        "fr": "On ne peut pas trouver d'info de l'appareil %s.",
        "it": "Non è possibile trovare informazioni da %s del dispositivo.",
        "es": "No se puede encontrar ninguna información de los %s del dispositivo.",
        "pl": "Nie można znaleźć żadnej informacji z urządzeń %s.",
        "uk": "Не знайти інформацію про пристрій %s.",
        "zh-cn": "坎特发现从装置中找到任何电缆 %s."
    },
    "getcurrent + tunerinfo": {
        "en": "getcurrent + tunerinfo: %s",
        "de": "getcurrent + tunerinfo: %s",
        "ru": "getcurrent + tunerinfo: %s",
        "pt": "getcurrent + tunerinfo: %s",
        "nl": "getcurrent + tunerinfo: %s",
        "fr": "getcurrent + tunerinfo: %s",
        "it": "getcurrent + tunerinfo: %s",
        "es": "getcurrent + tunerinfo: %s",
        "pl": "getcurrent + tunerinfo: %s",
        "uk": "getcurrent + tunerinfo: %s",
        "zh-cn": "getcurrent + tunerinfo: %s"
    },
    "Update deviceInfo": {
        "en": "Update deviceInfo %s.",
        "de": "Update deviceInfo %s.",
        "ru": "Обновление устройстваInfo %s.",
        "pt": "Dispositivo de atualizaçãoInfo %s.",
        "nl": "Update apparatuur %s.",
        "fr": "Update deviceInfo %s.",
        "it": "Aggiornare il dispositivoInfo %s.",
        "es": "Actualizar dispositivoInfo %s.",
        "pl": "Urządzenie Info %s.",
        "uk": "Оновлення пристроюInfo %s.",
        "zh-cn": "最新资料%s."
    },
    "Start Update deviceInfo": {
        "en": "Start Update deviceInfo %s.",
        "de": "Start Update deviceInfo %s.",
        "ru": "Начните обновление устройстваInfo %s.",
        "pt": "Iniciar dispositivo de atualizaçãoInfo %s.",
        "nl": "Start Update apparaat Info %s.",
        "fr": "Start Update deviceInfo %s.",
        "it": "Avviare il dispositivo di aggiornamentoInfo %s.",
        "es": "Start Update deviceInfo %s.",
        "pl": "Zastosowanie Info %s.",
        "uk": "Початок оновлення пристроюInfo %s.",
        "zh-cn": "B. 最新资料 %s."
    },
    "Request": {
        "en": "Request: %s",
        "de": "Anfrage: %s",
        "ru": "Запрос: %s",
        "pt": "Pedido: %s",
        "nl": "Verzoek: %s",
        "fr": "Demande: %s",
        "it": "Richiesta: %s",
        "es": "Solicitud: %s",
        "pl": "Request: %s",
        "uk": "Запит: %s",
        "zh-cn": "请求: %s"
    },
    "Response": {
        "en": "Response: %s",
        "de": "Antwort: %s",
        "ru": "Ответ: %s",
        "pt": "Resposta: %s",
        "nl": "Response: %s",
        "fr": "Réponse : %s",
        "it": "Risposta: %s",
        "es": "Respuesta: %s",
        "pl": "Response: %s",
        "uk": "Відповідь: %s",
        "zh-cn": "答复: %s"
    },
    "getRequest": {
        "en": "getRequest: %s",
        "de": "getRequest: %s",
        "ru": "getRequest: %s",
        "pt": "getRequest: %s",
        "nl": "getRequest: %s",
        "fr": "getRequest: %s",
        "it": "getRequest: %s",
        "es": "getRequest: %s",
        "pl": "getRequest: %s",
        "uk": "getRequest: %s",
        "zh-cn": "getRequest: %s"
    },
    "path": {
        "en": "Path: %s",
        "de": "Pfad: %s",
        "ru": "Путь: %s",
        "pt": "Caminho: %s",
        "nl": "Path:",
        "fr": "Sentier: %s",
        "it": "Percorso: %s",
        "es": "Sendero: %s",
        "pl": "Path: %s",
        "uk": "Шлях: %s",
        "zh-cn": "Path: %s"
    },
    "response sendCommand": {
        "en": "response sendCommand: %s",
        "de": "response sendCommand: %s",
        "ru": "response sendCommand: %s",
        "pt": "response sendCommand: %s",
        "nl": "response sendCommand: %s",
        "fr": "response sendCommand: %s",
        "it": "response sendCommand: %s",
        "es": "response sendCommand: %s",
        "pl": "response sendCommand: %s",
        "uk": "response sendCommand: %s",
        "zh-cn": "response sendCommand: %s"
    },
    "Command:": {
        "en": "Command: %s Device ID: %s",
        "de": "Befehl: %s Geräte-ID: %s",
        "ru": "Команда: %s ID устройства: %s",
        "pt": "Comando: %s ID do dispositivo: %s",
        "nl": "Commando: %s Device ID: %s",
        "fr": "Commandement: %s ID du dispositif: %s",
        "it": "Comando: %s ID dispositivo: %s",
        "es": "Comando: %s ID del dispositivo: %s",
        "pl": "Komenda: %s Device ID: %s",
        "uk": "Команда: %s Ідентифікатор пристрою: %s",
        "zh-cn": "指挥: %s 证人: %s"
    },
    "Receiver is Offline": {
        "en": "Receiver %s is Offline. Can't send a request!",
        "de": "Receiver %s ist Offline. Kann keine Anfrage senden!",
        "ru": "Приемник %s оффлайн. Не можете отправить заявку!",
        "pt": "Receiver %s está offline. Não posso enviar um pedido!",
        "nl": "Receiver %s is offline. Ik kan geen verzoek sturen!",
        "fr": "Le receveur %s est hors ligne. Je ne peux pas envoyer une demande !",
        "it": "Il ricevitore %s è offline. Non posso inviare una richiesta!",
        "es": "Receptor %s es Sin conexión. ¡No puedo enviar una petición!",
        "pl": "Receiver %s jest Offline. Nie może wysłać prośby!",
        "uk": "Приймач %s оффлайн. Не надішліть запит!",
        "zh-cn": "接受者%s人是线。 坎特发出请求!"
    },
    "Received unknown command": {
        "en": "Received unknown command %s for device %s",
        "de": "Unbekannter Befehl %s für Gerät %s empfangen",
        "ru": "Получена неизвестная команда %s для устройства %s",
        "pt": "Recebido comando desconhecido %s para dispositivo %s",
        "nl": "Onbekende commando %s voor apparaat %s",
        "fr": "Commande inconnue %s pour le dispositif %s",
        "it": "Ricevuto comando sconosciuto %s per dispositivo %s",
        "es": "Recibido comando desconocido %s para el dispositivo %s",
        "pl": "Nieznany dowódca %s dla urządzenia %s",
        "uk": "Надійшла невідома команда %s для пристрою %s",
        "zh-cn": "接收不明身份的车辆指挥 %s %s"
    },
    "Found file": {
        "en": "Found file %s",
        "de": "Gefundene Datei %s",
        "ru": "Найденный файл %s",
        "pt": "Arquivo encontrado %s",
        "nl": "Gevonden %s",
        "fr": "Trouvé fichier %s",
        "it": "Il file trovato %s",
        "es": "Archivo encontrado %s",
        "pl": "Plik %s",
        "uk": "Знайдено файл %s",
        "zh-cn": "档案 %s"
    },
    "File not found": {
        "en": "File not found: %s",
        "de": "Datei nicht gefunden: %s",
        "ru": "Файл не найден: %s",
        "pt": "Arquivo não encontrado: %s",
        "nl": "Geen bewijs gevonden: %s",
        "fr": "Fichier non trouvé: %s",
        "it": "File non trovato: %s",
        "es": "Archivo no encontrado: %s",
        "pl": "File nie odnaleziono: %s",
        "uk": "Файл не знайдено: %s",
        "zh-cn": "未发现: %s"
    },
    "Delete datapoint": {
        "en": "Delete datapoint %s",
        "de": "Löschen von Datenpunkt %s",
        "ru": "Удалить дата-точка %s",
        "pt": "Excluir datapoint %s",
        "nl": "Verwijder data %s",
        "fr": "Supprimer le point de données %s",
        "it": "Eliminare i dati %s",
        "es": "Eliminar el punto de datos %s",
        "pl": "Lista danych %s",
        "uk": "Видалення точок даних %s",
        "zh-cn": "删除数据点 %s"
    },
    "Filename not found": {
        "en": "Filename %s not found",
        "de": "Dateiname %s nicht gefunden",
        "ru": "Имя файла %s не найдено",
        "pt": "Nome do arquivo %s não encontrado",
        "nl": "Veldnaam %s niet gevonden.",
        "fr": "Nom de fichier %s non trouvé",
        "it": "Nome file %s non trovato",
        "es": "Nombre de archivo %s no encontrado",
        "pl": "Filename %s nie został znaleziony",
        "uk": "Ім'я файла %s не знайдено",
        "zh-cn": "第%s条"
    },
    "No filenames found in folder": {
        "en": "No filenames found in folder %s.",
        "de": "Keine Dateinamen im Ordner %s gefunden.",
        "ru": "Файлов не найдено в папке %s.",
        "pt": "Nenhum nome de arquivo encontrado na pasta %s.",
        "nl": "Geen dossiernamen gevonden in map %s.",
        "fr": "Aucun nom de fichier trouvé dans le dossier %s.",
        "it": "Nessun nome di file trovato nella cartella %s.",
        "es": "No se encontraron nombres de archivo en la carpeta %s.",
        "pl": "Nie ma nazwy plików w folderie %s.",
        "uk": "Не знайдено назв файлів в папці %s.",
        "zh-cn": "未发现的%s倍数。."
    },
    "Missing quality": {
        "en": "Missing quality %s.",
        "de": "Fehlende Qualität %s.",
        "ru": "Отсутствие качества %s.",
        "pt": "Qualidade de falta %s.",
        "nl": "Vermiste kwaliteit %s.",
        "fr": "La qualité manquante %s.",
        "it": "Qualità mancante %s.",
        "es": "Falta la calidad %s.",
        "pl": "Jakość %s.",
        "uk": "Якість промивання %s.",
        "zh-cn": "发布质量%s."
    },
    "Error": {
        "en": "Error %s - %s",
        "de": "Fehler %s - %s",
        "ru": "Ошибка %s - %s",
        "pt": "Erro %s - %s",
        "nl": "Error %s - %s",
        "fr": "Erreur %s - %s",
        "it": "Errore %s - %s",
        "es": "Error %s - %s",
        "pl": "Error %s - %s",
        "uk": "Про нас %s - %s",
        "zh-cn": "Error %s - %s"
    },
    "Folder": {
        "en": "Folder: %s",
        "de": "Ordner: %s",
        "ru": "Папка: %s",
        "pt": "Pasta: %s",
        "nl": "Folder: %s",
        "fr": "Folder: %s",
        "it": "Cartella: %s",
        "es": "Folder: %s",
        "pl": "Folder: %s",
        "uk": "Складv: %s",
        "zh-cn": "Folder: %s"
    },
    "Element": {
        "en": "Element: %s",
        "de": "Element: %s",
        "ru": "Элемент: %s",
        "pt": "Elemento: %s",
        "nl": "Element: %s",
        "fr": "Élément: %s",
        "it": "Elemento: %s",
        "es": "Elemento: %s",
        "pl": "Element: %s",
        "uk": "Навігація: %s",
        "zh-cn": "执行: %s"
    },
    "Change common": {
        "en": "Change common %s",
        "de": "Change common %s",
        "ru": "Change common %s",
        "pt": "Change common %s",
        "nl": "Change common %s",
        "fr": "Change common %s",
        "it": "Change common %s",
        "es": "Change common %s",
        "pl": "Change common %s",
        "uk": "Change common %s",
        "zh-cn": "Change common %s",
    },
    "Data": {
        "en": "Data: %s",
        "de": "Daten: %s",
        "ru": "Данные: %s",
        "pt": "Dados: %s",
        "nl": "Data: %s",
        "fr": "Données: %s",
        "it": "Dati: %s",
        "es": "Datos: %s",
        "pl": "Data: %s",
        "uk": "Дані: %s",
        "zh-cn": "数据: %s"
    },
    "Files": {
        "en": "Files: %s",
        "de": "Dateien: %s",
        "ru": "Файлы: %s",
        "pt": "Arquivos: %s",
        "nl": "Bestanden: %s",
        "fr": "Fichiers: %s",
        "it": "File: %s",
        "es": "Archivos: %s",
        "pl": "Archiwum: %s",
        "uk": "Файли: %s",
        "zh-cn": "电影: %s"
    },
    "Found file in iobroker database": {
        "en": "Found file in iobroker database: %s",
        "de": "Datei gefunden in iobroker Datenbank: %s",
        "ru": "Найден файл в базе iobroker: %s",
        "pt": "Encontrado arquivo no banco de dados iobroker: %s",
        "nl": "Gevonden in de database van de iobroker: %s",
        "fr": "Trouvé fichier dans la base de données iobroker: %s",
        "it": "File trovato nel database iobroker: %s",
        "es": "Archivo encontrado en la base de datos iobroker: %s",
        "pl": "Plik w iobroker bazy danych: %s",
        "uk": "Знайдено файл в базі даних iobroker: %s",
        "zh-cn": "罗伯克数据库的创始人: %s"
    },
    "database_delete": {
        "en": "Cannot found file in iobroker database! An attempt is made to delete the file: %s",
        "de": "Finde keine Datei in iobroker Datenbank! Es wird versucht, die Datei zu löschen: %s",
        "ru": "Не удалось найти файл в базе iobroker! Попытка сделана для удаления файла: %s",
        "pt": "Não encontrou arquivo no banco de dados iobroker! Uma tentativa é feita para excluir o arquivo: %s",
        "nl": "Kan geen dossier vinden in de database van de iobroker! Een poging is gemaakt om het dossier te wissen: %s",
        "fr": "Impossible trouvé le fichier dans la base de données iobroker ! Une tentative est faite pour supprimer le fichier: %s",
        "it": "Non è possibile trovare il file nel database iobroker! Un tentativo è fatto per eliminare il file: %s",
        "es": "No se puede encontrar archivo en la base de datos iobroker! Se intenta eliminar el archivo: %s",
        "pl": "Cannot znalazł plik w iobroker database. Próba usunięcia pliku: %s",
        "uk": "Не знайдено файл у базі даних iobroker! Здійснено спробу видалити файл: %s",
        "zh-cn": "吗? 有人试图删除档案。: %s"
    },
    "File deleted": {
        "en": "File deleted: %s",
        "de": "Datei gelöscht: %s",
        "ru": "Файл удален: %s",
        "pt": "Arquivo excluído: %s",
        "nl": "Bestand verwijderd: %s",
        "fr": "Fichier supprimé: %s",
        "it": "File cancellato: %s",
        "es": "Archivo eliminado: %s",
        "pl": "File usunąć: %s",
        "uk": "Видалити файл: %s",
        "zh-cn": "删除: %s"
    },
    "File not deleted": {
        "en": "File not deleted: %s",
        "de": "Datei nicht gelöscht: %s",
        "ru": "Файл не удален: %s",
        "pt": "Arquivo não excluído: %s",
        "nl": "Bestand niet gewist: %s",
        "fr": "Fichier non supprimé: %s",
        "it": "File non cancellato: %s",
        "es": "Archivo no eliminado: %s",
        "pl": "Archiwum nie usunęło się: %s",
        "uk": "Файл не видалено: %s",
        "zh-cn": "删除: %s"
    },
    "deletesnapshot obj": {
        "en": "deletesnapshot obj: %s",
        "de": "deletesnapshot obj: %s",
        "ru": "deletesnapshot obj: %s",
        "pt": "deletesnapshot obj: %s",
        "nl": "deletesnapshot obj: %s",
        "fr": "deletesnapshot obj: %s",
        "it": "deletesnapshot obj: %s",
        "es": "deletesnapshot obj: %s",
        "pl": "deletesnapshot obj: %s",
        "uk": "deletesnapshot obj: %s",
        "zh-cn": "deletesnapshot obj: %s"
    },
    "Data point deleted": {
        "en": "Data point deleted: %s",
        "de": "Datenpunkt gelöscht: %s",
        "ru": "Удалена точка данных: %s",
        "pt": "Ponto de dados excluído: %s",
        "nl": "Data punt gewist: %s",
        "fr": "Point de données supprimé: %s",
        "it": "Data point cancellato: %s",
        "es": "Punto de datos eliminado: %s",
        "pl": "Punkt danych usunął: %s",
        "uk": "Видалення точок даних: %",
        "zh-cn": "数据点删除: %s"
    },
    "Error deleting data point": {
        "en": "Error deleting data point: %",
        "de": "Fehler löschen Datenpunkt: %",
        "ru": "Ошибка удаления точки данных: %",
        "pt": "Erro de exclusão do ponto de dados: %",
        "nl": "Error verwijderen datapunt: %",
        "fr": "Point de données supprimé par erreur: %",
        "it": "Eliminazione di errore data point: %",
        "es": "Punto de datos de eliminación de errores: %",
        "pl": "Strona internetowa: %",
        "uk": "Помилка видалення даних: %",
        "zh-cn": "删除数据点: %"
    },
    "Command": {
        "en": "Command: %",
        "de": "Befehl: %",
        "ru": "Команда: %",
        "pt": "Comando: %",
        "nl": "Commando: %",
        "fr": "Commandant: %",
        "it": "Comando: %",
        "es": "Comando: %",
        "pl": "Dowództwo: %",
        "uk": "Про компанію: %",
        "zh-cn": "指挥: %"
    },
    "Cannot found Host IP": {
        "en": "Cannot found Host IP!",
        "de": "Host IP nicht gefunden!",
        "ru": "Не удалось найти Host IP!",
        "pt": "Não encontrou IP de host!",
        "nl": "Cannot vond Host IP!",
        "fr": "Je n'ai pas trouvé Host IP!",
        "it": "Non trovato Host IP!",
        "es": "¡No se puede encontrar Host IP!",
        "pl": "Cannot znalazł host IP!",
        "uk": "Не знайдено Хост IP!",
        "zh-cn": "失败的人质!"
    },
    "URL": {
        "en": "URL: %",
        "de": "URL: %",
        "ru": "URL: %",
        "pt": "URL: %",
        "nl": "URL: %",
        "fr": "URL: %",
        "it": "URL: %",
        "es": "URL: %",
        "pl": "URL: %",
        "uk": "КОНТАКТИ: %",
        "zh-cn": "URL: %"
    },
    "Start Promise": {
        "en": "Start Promise",
        "de": "Start Promise",
        "ru": "Start Promise",
        "pt": "Start Promise",
        "nl": "Start Promise",
        "fr": "Start Promise",
        "it": "Start Promise",
        "es": "Start Promise",
        "pl": "Start Promise",
        "uk": "Start Promise",
        "zh-cn": "Start Promise"
    },
    "Finish": {
        "en": "Finish",
        "de": "Finish",
        "ru": "Finish",
        "pt": "Finish",
        "nl": "Finish",
        "fr": "Finish",
        "it": "Finish",
        "es": "Finish",
        "pl": "Finish",
        "uk": "Finish",
        "zh-cn": "Finish"
    },
    "picpath": {
        "en": "picpath: %s",
        "de": "picpath: %s",
        "ru": "picpath: %s",
        "pt": "picpath: %s",
        "nl": "picpath: %s",
        "fr": "picpath: %s",
        "it": "picpath: %s",
        "es": "picpath: %s",
        "pl": "picpath: %s",
        "uk": "picpath: %s",
        "zh-cn": "picpath: %s"
    },
    "address": {
        "en": "address: %s",
        "de": "address: %s",
        "ru": "address: %s",
        "pt": "address: %s",
        "nl": "address: %s",
        "fr": "address: %s",
        "it": "address: %s",
        "es": "address: %s",
        "pl": "address: %s",
        "uk": "address: %s",
        "zh-cn": "address: %s"
    },
    "OK": {
        "en": "OK: %s",
        "de": "OK: %s",
        "ru": "OK: %s",
        "pt": "OK: %s",
        "nl": "OK: %s",
        "fr": "OK: %s",
        "it": "OK: %s",
        "es": "OK: %s",
        "pl": "OK: %s",
        "uk": "OK: %s",
        "zh-cn": "OK: %s"
    },
    "Create Snapshot": {
        "en": "Create Snapshot.",
        "de": "Snapshot erstellen.",
        "ru": "Создать снимок.",
        "pt": "Criar Instantâneo.",
        "nl": "Creëer Snapshot.",
        "fr": "Créer Snapshot.",
        "it": "Creare un'istantanea.",
        "es": "Crea Snapshot.",
        "pl": "Create Snapshot (ang.).",
        "uk": "Створити Snapshot.",
        "zh-cn": "创建绑架。."
    },
    "Snapshot not created": {
        "en": "Snapshot not created!",
        "de": "Snapshot nicht erstellt!",
        "ru": "Снимок не создан!",
        "pt": "Instantâneo não criado!",
        "nl": "Snapshot niet gemaakt!",
        "fr": "Snapshot not created!",
        "it": "Istantanee non create!",
        "es": "Snapshot no creado!",
        "pl": "Snapshot nie został stworzony!",
        "uk": "Знімок не створений!",
        "zh-cn": "绑架不是!"
    },
    "Timer": {
        "en": "Timer: %s",
        "de": "Timer: %s",
        "ru": "Таймер: %s",
        "pt": "Temporizador: %s",
        "nl": "Timer: %s",
        "fr": "Timer: %s",
        "it": "Timer: %s",
        "es": "Timer: %s",
        "pl": "Timer: %s",
        "uk": "Таймер: %s",
        "zh-cn": "时间: %s"
    },
    "Cleanup Timerlist": {
        "en": "Cleanup Timerlist.",
        "de": "Aufräumen Timerlist.",
        "ru": "Очистка таймерлиста.",
        "pt": "Lista de temporizadores de limpeza.",
        "nl": "Maak Timerlist schoon.",
        "fr": "Cleanup Timerlist.",
        "it": "Lista Timer Cleanup.",
        "es": "Lista de tiempo de limpieza.",
        "pl": "Cleanup Timerlist (ang.).",
        "uk": "Список таймерів очищення.",
        "zh-cn": "清洁时间名单。."
    },
    "Cant cleanup Timerlist": {
        "en": "Can't cleanup Timerlist.",
        "de": "Kann Timerlist nicht bereinigen.",
        "ru": "Не смогите очистить таймерлист.",
        "pt": "Não consigo limpar o Timerlist.",
        "nl": "Ik kan Timerlist niet opruimen.",
        "fr": "Je ne peux pas nettoyer Timerlist.",
        "it": "Non posso ripulire la Timerlist.",
        "es": "No puedo limpiar Timerlist.",
        "pl": "Nie może być tak naprawdę Timerlistą.",
        "uk": "Не можна чистити час.",
        "zh-cn": "Can't 清洁时间。."
    },
    "Create selected Timerlist": {
        "en": "Create selected Timerlist for %s.",
        "de": "Erstellen Sie ausgewählte Timerlist für %s1.",
        "ru": "Создать выбранный список Timerlist для %s.",
        "pt": "Criar Timerlist selecionada para %s.",
        "nl": "Creëer Timerlist voor %s.",
        "fr": "Créez un timerlist sélectionné pour %s.",
        "it": "Crea una lista temporale selezionata per %s.",
        "es": "Crear lista de tiempo seleccionada para %s.",
        "pl": "Create wybrał Timerlista na %s.",
        "uk": "Створіть вибраний список Timerlist для %s.",
        "zh-cn": "为%s名推选时名单. %s"
    },
    "new_states": {
        "en": "new_states: %s",
        "de": "new_states: %s",
        "ru": "new_states: %s",
        "pt": "new_states: %s",
        "nl": "new_states: %s",
        "fr": "new_states: %s",
        "it": "new_states: %s",
        "es": "new_states: %s",
        "pl": "new_states: %s",
        "uk": "new_states: %s",
        "zh-cn": "new_states: %s"
    },
    "Cannot create the selected timerlist": {
        "en": "Cannot create the selected timerlist.",
        "de": "Kann die ausgewählte Timerliste nicht erstellen.",
        "ru": "Не можете создать выбранный список таймера.",
        "pt": "Não é possível criar o timerlist selecionado.",
        "nl": "Kan de geselecteerde tijdlijst niet creëren.",
        "fr": "Ne peut pas créer le timerlist sélectionné.",
        "it": "Non è possibile creare la timerlist selezionata.",
        "es": "No se puede crear la lista de tiempo seleccionada.",
        "pl": "Cannot stworzył wybraną listę czasu.",
        "uk": "Не можна створювати вибраний список таймерів.",
        "zh-cn": "附加说明创建了选定的时间名单。."
    },
    "Not deleted": {
        "en": "Not deleted: %s",
        "de": "Nicht gelöscht: %s",
        "ru": "Не удаляется: %s",
        "pt": "Não excluído: %s",
        "nl": "Niet gewist: %s",
        "fr": "Non supprimé: %s",
        "it": "Non cancellato: %s",
        "es": "No se elimina: %s",
        "pl": "Nie usunąć: %s",
        "uk": "Не видалено: %s",
        "zh-cn": "删除: %s"
    },
    "Timerlist is empty": {
        "en": "Timerlist is empty",
        "de": "Timerlist ist leer",
        "ru": "Timerlist пуст",
        "pt": "Timerlist está vazio",
        "nl": "Timerlist is leeg",
        "fr": "Timerlist est vide",
        "it": "Timerlist è vuoto",
        "es": "Timerlist está vacío",
        "pl": "Timerlista jest pusta",
        "uk": "Часопис порожній",
        "zh-cn": "时间名单"
    },
    "Cannot read the timerlist": {
        "en": "Cannot read the Timerlist for %s.",
        "de": "Kann die Timerlist nicht für %s lesen.",
        "ru": "Не можете прочитать Timerlist для %s.",
        "pt": "Não consigo ler o Timerlist para %s.",
        "nl": "Kan de Timerlist niet lezen voor %s.",
        "fr": "Je ne peux pas lire le Timerlist pour %s.",
        "it": "Non è possibile leggere il Timerlist per %s.",
        "es": "No se puede leer el Timerlist para %s.",
        "pl": "Cannot czytał Timerlistę na %s.",
        "uk": "Не прочитайте Timerlist для %s.",
        "zh-cn": "传真:%s人."
    },
    "timer_json": {
        "en": "timer_json: %s",
        "de": "timer_json: %s",
        "ru": "timer_json: %s",
        "pt": "timer_json: %s",
        "nl": "timer_json: %s",
        "fr": "timer_json: %s",
        "it": "timer_json: %s",
        "es": "timer_json: %s",
        "pl": "timer_json: %s",
        "uk": "timer_json: %s",
        "zh-cn": "timer_json: %s"
    },
    "Cannot find Bouquets for the device": {
        "en": "Cannot find Bouquets for the device %s.",
        "de": "Kann Bouquets für das Gerät %s nicht finden.",
        "ru": "Не можете найти Букеты для устройства %s.",
        "pt": "Não é possível encontrar Bouquets para o dispositivo %s.",
        "nl": "Ik kan Bouquets niet vinden voor het apparaat %s.",
        "fr": "Ne trouvez pas Bouquets pour l'appareil %s.",
        "it": "Non riesco a trovare Bouquets per il dispositivo %s.",
        "es": "No se pueden encontrar Bouquets para el dispositivo %s.",
        "pl": "Cannot znajduje Bouquetsa dla urządzenia %s.",
        "uk": "Не можна знайти Букети для пристрою %s.",
        "zh-cn": "装置%s。."
    },
    "Create Bouquets and EPG": {
        "en": "Create Bouquets and EPG for the device %s.",
        "de": "Erstellen Sie Bouquets und EPG für das Gerät %s.",
        "ru": "Создать Букеты и EPG для устройства %s.",
        "pt": "Criar Bouquets e EPG para o dispositivo %s.",
        "nl": "Creëer Bouquets en EPG voor het apparaat %s.",
        "fr": "Créer Bouquets et EPG pour le dispositif %s.",
        "it": "Creare Bouquets e EPG per il dispositivo %s.",
        "es": "Crear ramos y EPG para el dispositivo %s.",
        "pl": "Create Bouquets i EPG dla urządzenia %s.",
        "uk": "Створіть букети і ЕПГ для пристрою %s.",
        "zh-cn": "D. 为装置设立Bquets和EPF %s."
    },
    "Loudness": {
        "en": "Loudness: %s",
        "de": "Lautstärke: %s",
        "ru": "Громкость: %s",
        "pt": "Loudness: %s",
        "nl": "Luidheid: %s",
        "fr": "Loudness: %s",
        "it": "Loudness: %s",
        "es": "Loudness: %s",
        "pl": "Sylwetka: %s",
        "uk": "Лудність: %s",
        "zh-cn": "损失: %s"
    },
    "Cannot set volume": {
        "en": "Can't set volume %s for device %s.",
        "de": "Das Volumen %s kann nicht für das Gerät %s eingestellt werden.",
        "ru": "Не могу установить объем %s для устройства %s.",
        "pt": "Não é possível definir o volume %s para o dispositivo %s.",
        "nl": "Ik kan geen %s voor apparaat %s zetten.",
        "fr": "Impossible de définir le volume %s pour le dispositif %s.",
        "it": "Non è possibile impostare il volume %s per il dispositivo %s.",
        "es": "No se puede configurar el volumen %s para el dispositivo %s.",
        "pl": "Nie ustalono numeru %s dla urządzenia %s.",
        "uk": "Не можна встановити об'єм %s для пристрою %s.",
        "zh-cn": "装置%s件编号%s."
    },
    "Cannot set powerstate": {
        "en": "Cannot set powerstate: %s",
        "de": "Kann Powerstate nicht setzen: %s",
        "ru": "Не может установить powerstate: %s",
        "pt": "Não pode definir powerstate: %s",
        "nl": "Kan geen stroomstoring veroorzaken: %s",
        "fr": "Ne peut pas définir l'état de puissance: %s",
        "it": "Non può impostare stato di potenza: %s",
        "es": "No puede establecer el poder: %s",
        "pl": "Cannot set powerstate (ang.) %s",
        "uk": "Не можна встановити потужністьстату: %s",
        "zh-cn": "附加规定的权力国: %s"
    },
    "Missing eventid": {
        "en": "Missing eventid",
        "de": "Fehlende Eventid",
        "ru": "Отсутствие eventid",
        "pt": "Evento perdido",
        "nl": "Vermiste gebeurtenis",
        "fr": "Missing eventid",
        "it": "Missing eventid",
        "es": "Desaparecidos",
        "pl": "Missing eventid",
        "uk": "Місячний захід",
        "zh-cn": "失踪事件"
    },
    "Missing sRef": {
        "en": "Missing sRef",
        "de": "Fehlendes sRef",
        "ru": "Отсутствие sRef",
        "pt": "Faltando sRef",
        "nl": "Vermist sRef",
        "fr": "Missing sRef",
        "it": "SRef mancante",
        "es": "Missing sRef",
        "pl": "Missing sRef",
        "uk": "Місячний sRef",
        "zh-cn": "失踪"
    },
    "Set Record": {
        "en": "Set Record: %s",
        "de": "Set Record: %s",
        "ru": "Установить рекорд: %s",
        "pt": "Registro de Conjunto: %s",
        "nl": "Set Record: %s",
        "fr": "Ensemble: %s",
        "it": "Set Record: %s",
        "es": "Set Record: %s",
        "pl": "Okładka: %s",
        "uk": "Запис: %s",
        "zh-cn": "简要记录: %s"
    }
    ,
    "state.val": {
        "en": "state.val: %s",
        "de": "state.val: %s",
        "ru": "state.val: %s",
        "pt": "state.val: %s",
        "nl": "state.val: %s",
        "fr": "state.val: %s",
        "it": "state.val: %s",
        "es": "state.val: %s",
        "pl": "state.val: %s",
        "uk": "state.val: %s",
        "zh-cn": "state.val: %s"
    },
    "rec.native.epg": {
        "en": "rec.native.epg: %s",
        "de": "rec.native.epg: %s",
        "ru": "rec.native.epg: %s",
        "pt": "rec.native.epg: %s",
        "nl": "rec.native.epg: %s",
        "fr": "rec.native.epg: %s",
        "it": "rec.native.epg: %s",
        "es": "rec.native.epg: %s",
        "pl": "rec.native.epg: %s",
        "uk": "rec.native.epg: %s",
        "zh-cn": "rec.native.epg: %s"
    },
    "epgservice.events": {
        "en": "epgservice.events: %s",
        "de": "epgservice.events: %s",
        "ru": "epgservice.events: %s",
        "pt": "epgservice.events: %s",
        "nl": "epgservice.events: %s",
        "fr": "epgservice.events: %s",
        "it": "epgservice.events: %s",
        "es": "epgservice.events: %s",
        "pl": "epgservice.events: %s",
        "uk": "epgservice.events: %s",
        "zh-cn": "epgservice.events: %s"
    },
    "Select Movies": {
        "en": "Select Movies: %s",
        "de": "Filme auswählen: %s",
        "ru": "Выбрать фильмы: %s",
        "pt": "Selecione filmes: %s",
        "nl": "Select Movies: %s",
        "fr": "Sélectionnez les films: %s",
        "it": "Seleziona film: %s",
        "es": "Seleccione películas: %s",
        "pl": "Wybrane filmy: %s",
        "uk": "Виберіть кіно: %s",
        "zh-cn": "Select Movies: %s"
    },
    "The status deepstandby": {
        "en": "The status deepstandby is set for the device %s and a new interval for %s seconds.",
        "de": "Der Status Deepstandby wird für das Gerät %s gesetzt und ein neuer Intervall für %s Sekunden eingestellt.",
        "ru": "Статус deepstandby установлен на устройство %s и новый интервал в течение %s секунд.",
        "pt": "O status deepstandby é definido para o dispositivo %s e um novo intervalo por %s segundos.",
        "nl": "De status is klaar voor het apparaat %s en een nieuwe interval voor %s seconden.",
        "fr": "L'état du support est fixé pour le dispositif %s et un nouvel intervalle pendant %s secondes.",
        "it": "Lo stato deepstandby è impostato per il dispositivo %s e un nuovo intervallo per %s secondi.",
        "es": "El estado de profundidad se establece para el dispositivo %s y un nuevo intervalo durante %s segundos.",
        "pl": "Status głęboka jest ustawiony dla urządzenia %s i nowego przedziału na %s sekund.",
        "uk": "Для пристрою %s і нового інтервалу за %s секунд.",
        "zh-cn": "装置%s和%s秒钟的新的间隔规定了深层待命状态。."
    },
    "Set new Status": {
        "en": "The status for device %s is set online and a new interval of %s seconds.",
        "de": "Der Status für das Gerät %s wird online und ein neues Intervall von %s Sekunden eingestellt.",
        "ru": "Статус на устройство %s установлен онлайн и новый интервал %s секунд.",
        "pt": "O status do dispositivo %s é definido on-line e um novo intervalo de %s segundos.",
        "nl": "De status voor apparaat %s is online gezet en een nieuwe interval van %s seconden.",
        "fr": "Le statut du périphérique %s est défini en ligne et un nouvel intervalle de %s secondes.",
        "it": "Lo stato del dispositivo %s è impostato online e un nuovo intervallo di %s secondi.",
        "es": "El estado para el dispositivo %s se establece en línea y un nuevo intervalo de %s segundos.",
        "pl": "Status urządzenia %s jest osadzony w Internecie, a nowy przedział %s sekund.",
        "uk": "Для пристрою %s встановлюється статус онлайн і новий інтервал %s секунд.",
        "zh-cn": "装置%s的地位是在线确定的,是%s秒的新间隔。."
    },
    "WOL signal sent": {
        "en": "WOL signal sent: %s",
        "de": "WOL Signal gesendet: %s",
        "ru": "WOL сигнал отправлен: %s",
        "pt": "Sinal WOL enviado: %s",
        "nl": "WOL signaal: %s",
        "fr": "Signal WOL envoyé: %s",
        "it": "Segnale WOL inviato: %s",
        "es": "WOL signal sent: %s",
        "pl": "Sygnał WOL: %s",
        "uk": "Відправити сигнал: %s",
        "zh-cn": "WOL发出的信号: %s"
    },
    "Response your Request": {
        "en": "Response your Request: %s",
        "de": "Antworte auf deine Anfrage: %s",
        "ru": "Ответ ваш Запрос: %s",
        "pt": "Responda à sua Pedido: %s",
        "nl": "Verantwoord je Verzoek: %s",
        "fr": "Réponse Demande: %s",
        "it": "Rispondete Richiesta: %s",
        "es": "Respuesta a su Solicitud: %s",
        "pl": "Posłuchaj wasz Request: %s",
        "uk": "Відповіді Запит: %s",
        "zh-cn": "答复 请求: %s"
    },
    "Message empty": {
        "en": "Message from device %s is empty.",
        "de": "Die Nachricht vom Gerät %s ist leer.",
        "ru": "Сообщение с устройства %s пусто.",
        "pt": "A mensagem do dispositivo %s está vazia.",
        "nl": "Bericht van apparaat %s is leeg.",
        "fr": "Message du dispositif %s est vide.",
        "it": "Il messaggio dal dispositivo %s è vuoto.",
        "es": "El mensaje del dispositivo %s está vacío.",
        "pl": "Pojazd z urządzenia %s jest pusty.",
        "uk": "Повідомлення від пристрою %s порожній.",
        "zh-cn": "来自装置%s的邮件是空洞的。."
    },
    "Message type": {
        "en": "Message type from device %s not found.",
        "de": "Nachrichtentyp aus Gerät %s nicht gefunden.",
        "ru": "Тип сообщения с устройства %s не найдено.",
        "pt": "Tipo de mensagem do dispositivo %s não encontrado.",
        "nl": "Bericht type van apparaat %s niet gevonden.",
        "fr": "Type de message du périphérique %s non trouvé.",
        "it": "Tipo di messaggio dal dispositivo %s non trovato.",
        "es": "Tipo de mensaje del dispositivo %s no encontrado.",
        "pl": "Z urządzeniem %s nie znaleziono.",
        "uk": "Тип повідомлення від пристрою %s не знайдено.",
        "zh-cn": "未发现的%s种装置的车辆类型。."
    },
    "Message Timeout": {
        "en": "Message Timeout from device %s not found.",
        "de": "Nachricht Timeout von Gerät %s nicht gefunden.",
        "ru": "Сообщение Timeout с устройства %s не найдено.",
        "pt": "Mensagem Timeout do dispositivo %s não encontrado.",
        "nl": "Bericht van apparaat %s, niet gevonden.",
        "fr": "Message Timeout de l'appareil %s non trouvé.",
        "it": "Messaggio Timeout dal dispositivo %s non trovato.",
        "es": "Mensaje del dispositivo %s no encontrado.",
        "pl": "Czas wyjścia z urządzenia %s nie został znaleziony.",
        "uk": "Час відправлення з пристрою %s не знайдено.",
        "zh-cn": "未发现的%s台装置的及时性。."
    },
    "Message answer": {
        "en": "Message answer: %s",
        "de": "Nachricht: %s",
        "ru": "Ответ на сообщение: %s",
        "pt": "Resposta da mensagem: %s",
        "nl": "Bericht: %s",
        "fr": "Réponse du message : %s",
        "it": "Messaggio risposta: %s",
        "es": "Respuesta del mensaje: %s",
        "pl": "Odpowiedź: %s",
        "uk": "Відповідь на повідомлення: %s",
        "zh-cn": "答案: %s"
    },
    "Command 108": {
        "en": "Command 108: %s",
        "de": "Befehl 108: %s",
        "ru": "Команда 108: %s",
        "pt": "Comando 108: %s",
        "nl": "Command 108: %s",
        "fr": "Commande 108: %s",
        "it": "Comando 108: %s",
        "es": "Comando 108: %s",
        "pl": "Dowództwo 108: %s",
        "uk": "Команда 108: %s",
        "zh-cn": "指挥108: %s"
    },
    "ZAPandEPG": {
        "en": "ZAPandEPG: %s",
        "de": "ZAPandEPG: %s",
        "ru": "ZAPandEPG: %s",
        "pt": "ZAPandEPG: %s",
        "nl": "ZAPandEPG: %s",
        "fr": "ZAPandEPG: %s",
        "it": "ZAPandEPG: %s",
        "es": "ZAPandEPG: %s",
        "pl": "ZAPandEPG: %s",
        "uk": "ZAPandEPG: %s",
        "zh-cn": "ZAPandEPG: %s"
    },
    "ZAPandEPG event": {
        "en": "ZAPandEPG event: %s",
        "de": "ZAPandEPG event: %s",
        "ru": "ZAPandEPG event: %s",
        "pt": "ZAPandEPG event: %s",
        "nl": "ZAPandEPG event: %s",
        "fr": "ZAPandEPG event: %s",
        "it": "ZAPandEPG event: %s",
        "es": "ZAPandEPG event: %s",
        "pl": "ZAPandEPG event: %s",
        "uk": "ZAPandEPG event: %s",
        "zh-cn": "ZAPandEPG event: %s"
    },
    "getservices": {
        "en": "getservices: %s",
        "de": "getservices: %s",
        "ru": "getservices: %s",
        "pt": "getservices: %s",
        "nl": "getservices: %s",
        "fr": "getservices: %s",
        "it": "getservices: %s",
        "es": "getservices: %s",
        "pl": "getservices: %s",
        "uk": "getservices: %s",
        "zh-cn": "getservices: %s"
    },
    "Please select SIMPLE-API": {
        "en": "Please select SIMPLE-API in your instance config!",
        "de": "Bitte wählen Sie SIMPLE-API in Ihrer Instanz config!",
        "ru": "Пожалуйста, выберите SIMPLE-API в вашем примере config!",
        "pt": "Por favor, selecione SIMPLE-API em sua configuração de instância!",
        "nl": "Kies SIMPLE-API in uw instance config!",
        "fr": "Veuillez sélectionner SIMPLE-API dans votre configuration d'instance !",
        "it": "Seleziona SIMPLE-API nella configurazione delle istanze!",
        "es": "Por favor, seleccione SIMPLE-API en su configuración de instancia!",
        "pl": "Wybierz pliki SIMPLE-API w twojej konfigubie!",
        "uk": "Будь ласка, виберіть SIMPLE-API в налаштуваннях вашого екземпляра!",
        "zh-cn": "请选择SILE-API in 你的榜样!"
    },
    "Cannot found SIMPLE-API": {
        "en": "Cannot found SIMPLE-API: %s",
        "de": "Nicht gefunden SIMPLE-API: %s",
        "ru": "Не можете найти SIMPLE-API: %s",
        "pt": "Não encontrou SIMPLE-API: %s",
        "nl": "Kan niet SIMPLE-API vinden: %s",
        "fr": "Vous n'avez pas trouvé SIMPLE-API: %s",
        "it": "Non trovato SIMPLE-API: %s",
        "es": "No se encuentra SIMPLE-API: %s",
        "pl": "Cannot znalazł SIMPLE-API: %s",
        "uk": "Не знайдено SIMPLE-API: %s",
        "zh-cn": "堪称“SIMPLE-API: %s"
    },
    "Use SIMPLE-API without authorization": {
        "en": "Use SIMPLE-API without authorization! %s",
        "de": "Verwenden Sie SIMPLE-API ohne Berechtigung! %s",
        "ru": "Используйте SIMPLE-API без авторизации! %s",
        "pt": "Use SIMPLE-API sem autorização! %s",
        "nl": "Gebruik SIMPLE-API zonder toestemming! %s",
        "fr": "Utilisez SIMPLE-API sans autorisation! %s",
        "it": "Utilizzare SIMPLE-API senza autorizzazione! %s",
        "es": "Utilice SIMPLE-API sin autorización! %s",
        "pl": "Użycie SIMPLE bez autoryzacji! %s",
        "uk": "Використовуйте SIMPLE-API без авторизації! %s",
        "zh-cn": "不经授权使用SILE-API! %s"
    },
    "Missing IP or Username": {
        "en": "Missing IP or Username!",
        "de": "IP oder Benutzername nicht gefunden!",
        "ru": "Отсутствует IP или имя пользователя!",
        "pt": "Falta de IP ou nome de usuário!",
        "nl": "Vermist IP of Usernaam!",
        "fr": "Manque IP ou nom d'utilisateur!",
        "it": "Nome utente o IP mancante!",
        "es": "¡Perdiendo IP o nombre de usuario!",
        "pl": "Missing IP or Username (ang.)!",
        "uk": "Ім'я користувача!",
        "zh-cn": "MississIP或用户!"
    },
    "Cannot read file": {
        "en": "Cannot read file: %s - %s",
        "de": "Kann Datei nicht lesen: %s - %s",
        "ru": "Не могу читать файл: %s - %s",
        "pt": "Não é possível ler arquivo: %s - %s",
        "nl": "Kan geen dossier lezen: %s - %s",
        "fr": "Ne peut pas lire le fichier: %s - %s",
        "it": "Non riesco a leggere il file: %s - %s",
        "es": "No se puede leer el archivo: %s - %s",
        "pl": "Czytaj plik: %s - %s",
        "uk": "Не прочитати файл: %s - %s",
        "zh-cn": "评 注: %s - %s"
    },
    "Cannot create filename": {
        "en": "Cannot create filename for device %s.",
        "de": "Kann Dateiname für Gerät %s nicht erstellen.",
        "ru": "Не можете создать имя файла для устройства %s.",
        "pt": "Não é possível criar nome de arquivo para dispositivo %s.",
        "nl": "Ik kan geen dossiernaam maken voor apparaat %s.",
        "fr": "Ne peut pas créer de nom de fichier pour le périphérique %s.",
        "it": "Non può creare il nome del file per il dispositivo %s.",
        "es": "No se puede crear nombre de archivo para el dispositivo %s.",
        "pl": "Cannot stworzył nazwę pliku %s.",
        "uk": "Неможливо створити ім'я файлу для пристрою %s.",
        "zh-cn": "制造装置的编号为%s."
    },
    "Connection established": {
        "en": "Connection established for device %s.",
        "de": "Verbindung für Gerät %s hergestellt.",
        "ru": "Подключение установлено для устройства %s.",
        "pt": "Conexão estabelecida para o dispositivo %s.",
        "nl": "Verbinding gevestigd voor apparaat %s.",
        "fr": "Connexion établie pour le dispositif %s.",
        "it": "Connessione stabilita per dispositivo %s.",
        "es": "Conexión establecida para el dispositivo %s.",
        "pl": "Związany do urządzenia %s.",
        "uk": "Підключення, встановлене для пристрою %s.",
        "zh-cn": "为装置 %s建立起来。."
    },
    "Replace:": {
        "en": "Replace: %s - Device: %s",
        "de": "Ersetzen: %s - Device: %s",
        "ru": "Заменить: %s - Device: %s",
        "pt": "Substituir: %s - Device: %s",
        "nl": "Vervang: %s - Device: %s",
        "fr": "Remplacer: %s - Device: %s",
        "it": "Sostituire: %s - Device: %s",
        "es": "Reemplazar: %s - Device: %s",
        "pl": "Replace: %s - Device: %s",
        "uk": "Замінити: %s - Device: %s",
        "zh-cn": "改为: %s - Device: %s"
    },
    "Response:": {
        "en": "Response: %s - Device: %s",
        "de": "Antwort: %s - Device: %s",
        "ru": "Ответ: %s - Device: %s",
        "pt": "Resposta: %s - Device: %s",
        "nl": "Response: %s - Device: %s",
        "fr": "Réponse : %s - Device: %s",
        "it": "Risposta: %s - Device: %s",
        "es": "Respuesta: %s - Device: %s",
        "pl": "Response: %s - Device: %s",
        "uk": "Відповідь: %s - Device: %s",
        "zh-cn": "答复: %s - Device: %s"
    },
    "Set SSH_CREATED": {
        "en": "Set Datapoint SSH_CREATED true for device %s.",
        "de": "Setze Datapoint SSH_CREATED auf wahr für das Gerät %s.",
        "ru": "Установить Datapoint SSH_CREATED верно для устройства %s.",
        "pt": "Definir Datapoint SSH_CREATED verdadeiro para o dispositivo %s.",
        "nl": "Stel Datapoint SSH_CREATED waar in voor apparaat %s.",
        "fr": "Set Datapoint SSH_CREATED vrai pour l'appareil %s.",
        "it": "Impostare Datapoint SSH_CREATED vero per il dispositivo %s.",
        "es": "Establecer el punto de datos SSH_CREATED verdadero para el dispositivo %s.",
        "pl": "Set Datapoint SSH_CREATED. Prawdziwe dla urządzenia %s.",
        "uk": "Налаштування точок даних SSH_CREATED true для пристрою %s.",
        "zh-cn": "一套数据点SSH_CREA B. 真正的装置 %s."
    },
    "Set chmod 775": {
        "en": "Set chmod 775 for /home/%s.sh",
        "de": "Set chmod 775 für /home/%s.sh",
        "ru": "Установите chmod 775 для /home/%s.sh",
        "pt": "Definir chmod 775 para /home/%s.sh",
        "nl": "Set chmod 775 /home/%s.sh",
        "fr": "Set chmod 775 for /home/%s.sh",
        "it": "Set chmod 775 per /home/%s.sh",
        "es": "Set chmod 775 para /home/%s.sh",
        "pl": "Set chmod 775 for /home/%s.sh",
        "uk": "Набір chmod 775 для /home/%s.sh",
        "zh-cn": "A. 古柯775 /home/%s.sh"
    },
    "Files and symlinks": {
        "en": "Files and symlinks for device %s created.",
        "de": "Dateien und Symlinks für Gerät %s erstellt.",
        "ru": "Файлы и ссылки для устройства %s созданы.",
        "pt": "Arquivos e symlinks para dispositivo %s criado.",
        "nl": "Bestanden en symlinks voor apparaat %s gemaakt.",
        "fr": "Fichiers et liens pour le périphérique %s créé.",
        "it": "File e simlink per il dispositivo %s creato.",
        "es": "Archivos y enlaces para el dispositivo %s creado.",
        "pl": "Utwory i linki do urządzenie %s.",
        "uk": "Файли та симлінки для пристрою %s створено.",
        "zh-cn": "装置%s的电影和不对称。."
    },
    "Cant Files and symlinks": {
        "en": "Can't Files and symlinks for device %s created: %s",
        "de": "Kann keine Dateien und Symlinks für Gerät %s erstellt: %s",
        "ru": "Не смогите файлы и ссылки для устройства %s созданного: %s",
        "pt": "Não é possível arquivos e symlinks para o dispositivo %s criado: %s",
        "nl": "Kan geen Files en symlinks voor apparaat %s gemaakt: %s",
        "fr": "Impossible Fichiers et liens de sym pour le périphérique %s créé: %s",
        "it": "Non è possibile creare file e collegamenti per il dispositivo %s: %s",
        "es": "No se pueden crear archivos y simbolos para el dispositivo %s: %s",
        "pl": "Nie mogą tworzyć plików i połączenia do urządzenia %s: %s",
        "uk": "Чи не можна використовувати файли та symlinks для пристрою %s: %s",
        "zh-cn": "制造了%s种装置的Cat Files和不对称。: %s"
    },
    "Delete files and symlinks": {
        "en": "Delete files and symlinks for device %s.",
        "de": "Löschen von Dateien und Symlinks für Gerät %s.",
        "ru": "Удалить файлы и ссылки для устройства %s.",
        "pt": "Excluir arquivos e links para dispositivo %s.",
        "nl": "Verwijder de bestanden en symlinken voor apparaat %s.",
        "fr": "Supprimer les fichiers et les liens pour le périphérique %s.",
        "it": "Eliminare i file e i collegamenti simlink per il dispositivo %s.",
        "es": "Eliminar archivos y enlaces para el dispositivo %s.",
        "pl": "Pliki Delete i linki do urządzenia %s.",
        "uk": "Видалити файли і симлінки для пристрою %s.",
        "zh-cn": "删除装置的档案和不对称问题%s."
    },
    "Error deleting files and symlinks": {
        "en": "Error deleting files and symlinks from device %s: %s",
        "de": "Fehler beim Löschen von Dateien und Symlinks vom Gerät %s: %s",
        "ru": "Ошибка удаления файлов и ссылки с устройства %s: %s",
        "pt": "Erro de exclusão de arquivos e symlinks do dispositivo %s: %s",
        "nl": "Error verwijdert dossiers en symlinks van apparaat %s: %s",
        "fr": "Erreur de supprimer les fichiers et les liens de symlink de l'appareil %s: %s",
        "it": "Cancellazione di errore file e collegamenti simlink dal dispositivo %s: %s",
        "es": "Eliminar archivos de error y enlaces de enlace desde el dispositivo %s: %s",
        "pl": "Error deleting files and symlinks from device %s: %s",
        "uk": "Видаляє файли і симлінії від пристрою %s: %s",
        "zh-cn": "第%s条. 删除档案和装置的不对称。: %s"
    },
    "Delete file": {
        "en": "Delete /home/%s.sh for device %s.",
        "de": "Löschen Sie /home/%s.sh für Gerät %s.",
        "ru": "Удалить /home/%s.sh для устройства %s.",
        "pt": "Excluir /home/%s.sh para dispositivo %s.",
        "nl": "Verwijder /home/%s.sh voor apparaat %s.",
        "fr": "Supprimer /home/%s.sh pour le périphérique %s.",
        "it": "Elimina /home/%s.sh per il dispositivo %s.",
        "es": "Eliminar /home/%s.sh para el dispositivo %s.",
        "pl": "Delete /home/%s.sh dla urządzenia %s.",
        "uk": "Видалити /home/%s.sh для пристрою %s.",
        "zh-cn": "删去/home/%s.sh装置 %s。."
    },
    "Set Datapoint SSH_CREATED to false": {
        "en": "Set Datapoint SSH_CREATED to false. Device: %s",
        "de": "Setze Datapoint SSH_CREATED auf false. Device: %s",
        "ru": "Установите Datapoint SSH_CREATED на false. Device: %s",
        "pt": "Defina Datapoint SSH_CREATED para false. Device: %s",
        "nl": "Zet datapoint SSH op vals. Device: %s",
        "fr": "Définir Datapoint SSH_CREATED à false. Device: %s",
        "it": "Impostare Datapoint SSH_CREATED al falso. Device: %s",
        "es": "Establecer Datapoint SSH_CREATED a false. Device: %s",
        "pl": "Set Datapoint SSH_CREATED to false. Device: %s",
        "uk": "Встановити точку даних SSH_CREATED до false. Device: %s",
        "zh-cn": "数据点SSH_CREA反恐. Device: %s"
    },
    "commandToSSH2": {
        "en": "commandToSSH2: %s",
        "de": "commandToSSH2: %s",
        "ru": "commandToSSH2: %s",
        "pt": "commandToSSH2: %s",
        "nl": "commandToSSH2: %s",
        "fr": "commandToSSH2: %s",
        "it": "commandToSSH2: %s",
        "es": "commandToSSH2: %s",
        "pl": "commandToSSH2: %s",
        "uk": "commandToSSH2: %s",
        "zh-cn": "commandToSSH2: %s"
    },
    "Delete Record Interval": {
        "en": "Delete Record Interval for device %s. Status: %s",
        "de": "Löschen Sie Record Interval für Gerät %s. Status: %s",
        "ru": "Удалить Interval записи для устройства %s. Статус: %s",
        "pt": "Excluir Intervalo de registro para dispositivo %s. Estado: %s",
        "nl": "Delete Record Interval voor apparaat %s. Status: %s",
        "fr": "Supprimer Record Interval pour le périphérique %s. État : %s",
        "it": "Elimina Intervallo record per il dispositivo %s. Stato: %s",
        "es": "Eliminar Interval de grabación para el dispositivo %s. Situación: %s",
        "pl": "Delete Record Interval for device %s. Status: %s",
        "uk": "Видалити запис Interval для пристрою %s. Статус: %s",
        "zh-cn": "删除装置的录音记录 %s. 现状: %s"
    },
    "Set ack": {
        "en": "Set ack=True: %s",
        "de": "Set ack=True: %s",
        "ru": "Set ack=True: %s",
        "pt": "Set ack=True: %s",
        "nl": "Set ack=True: %s",
        "fr": "Set ack=True: %s",
        "it": "Set ack=True: %s",
        "es": "Set ack=True: %s",
        "pl": "Set ack=True: %s",
        "uk": "Set ack=True: %s",
        "zh-cn": "Set ack=True: %s"
    },
    "Delete updateInterval": {
        "en": "Delete updateInterval for Device %s.",
        "de": "UpdateInterval für Gerät %s gelöscht.",
        "ru": "Удалить обновлениеИнтервал для устройства %s.",
        "pt": "Excluir updateInterval for Device %s.",
        "nl": "Verwijder update voor Device %s.",
        "fr": "Supprimer la mise à jourInterval for Device %s.",
        "it": "Eliminare l'aggiornamentoIntervallo per il dispositivo %s.",
        "es": "Eliminar actualizaciónIntervalo para el dispositivo %s.",
        "pl": "Wspomnienienie w wersji %s.",
        "uk": "Видалити оновленняInterval для пристрою %s.",
        "zh-cn": "删除Device的更新接口%s."
    },
    "Data point quality is cleaned up": {
        "en": "Data point quality is cleaned up.",
        "de": "Datenpunkt Qualität wird bereinigt.",
        "ru": "Качество точки данных очищается.",
        "pt": "A qualidade do ponto de dados é limpa.",
        "nl": "Datapunt kwaliteit is opgeruimd.",
        "fr": "La qualité du point de données est nettoyée.",
        "it": "La qualità del punto di dati viene ripulita.",
        "es": "La calidad del punto de datos está limpiada.",
        "pl": "Jakość danych jest oczyszczona.",
        "uk": "Якість точки даних очищається.",
        "zh-cn": "数据点质量是清洁的。."
    },
    "Datapoint": {
        "en": "Datapoint: %s",
        "de": "Datapoint: %s",
        "ru": "Datapoint: %s",
        "pt": "Datapoint: %s",
        "nl": "Datapoint: %s",
        "fr": "Datapoint: %s",
        "it": "Datapoint: %s",
        "es": "Datapoint: %s",
        "pl": "Datapoint: %s",
        "uk": "Призначення: %s",
        "zh-cn": "数据点: %s"
    },
    "Found:": {
        "en": "Found: %s",
        "de": "Gefunden: %s",
        "ru": "Найдено: %s",
        "pt": "Encontrei: %s",
        "nl": "Gevonden: %s",
        "fr": "Trouvé: %s",
        "it": "Trovato: %s",
        "es": "Encontrado: %s",
        "pl": "Założyciel: %s",
        "uk": "Знайдено: %s",
        "zh-cn": "创始人: %s"
    },
    "The Datapoint State is empty": {
        "en": "The Datapoint State is empty.",
        "de": "Der Datapoint State ist leer.",
        "ru": "Государство Datapoint пусто.",
        "pt": "O Estado Datapoint está vazio.",
        "nl": "De Datapoint State is leeg.",
        "fr": "L'État Datapoint est vide.",
        "it": "Lo Stato Datapoint è vuoto.",
        "es": "El Estado Datapoint está vacío.",
        "pl": "Stan danych jest pusty.",
        "uk": "Стан даних порожній.",
        "zh-cn": "数据点国家是空洞的。."
    },
    "sendLucky": {
        "en": "sendLucky: %s",
        "de": "sendLucky: %s",
        "ru": "sendLucky: %s",
        "pt": "sendLucky: %s",
        "nl": "sendLucky: %s",
        "fr": "sendLucky: %s",
        "it": "sendLucky: %s",
        "es": "sendLucky: %s",
        "pl": "sendLucky: %s",
        "uk": "sendLucky: %s",
        "zh-cn": "sendLucky: %s"
    },
    "response sendLucky": {
        "en": "response sendLucky: %s",
        "de": "response sendLucky: %s",
        "ru": "response sendLucky: %s",
        "pt": "response sendLucky: %s",
        "nl": "response sendLucky: %s",
        "fr": "response sendLucky: %s",
        "it": "response sendLucky: %s",
        "es": "response sendLucky: %s",
        "pl": "response sendLucky: %s",
        "uk": "response sendLucky: %s",
        "zh-cn": "response sendLucky: %s"
    },
    "Start time": {
        "en": "Start time: %s",
        "de": "Startzeit: %s",
        "ru": "Начало: %s",
        "pt": "Tempo de início: %s",
        "nl": "Begin de tijd: %s",
        "fr": "Temps de démarrage: %s",
        "it": "Inizio: %s",
        "es": "Hora de inicio: %s",
        "pl": "Od razu: %s",
        "uk": "Час початку: %s",
        "zh-cn": "启动时间: %s"
    }
};
