exports.trans = {
    "Encrypt": {
        "en": "Encryption of all passwords done!",
        "de": "Verschlüsselung aller Passwörter!",
        "ru": "Шифрование всех паролей!",
        "pt": "Criptografia de todas as senhas feitas!",
        "nl": "Encryptie van alle wachtwoorden!",
        "fr": "Cryptage de tous les mots de passe !",
        "it": "Crittografia di tutte le password fatte!",
        "es": "¡Encriptación de todas las contraseñas hechas!",
        "pl": "Wszystko o wszystkich hasłach zrobiono!",
        "uk": "Зашифрування всіх паролів зроблено!",
        "zh-cn": "摘录所有密码!"
    },
    "Device_disabled": {
        "en": "Device %s is disabled.",
        "de": "Gerät %s ist deaktiviert.",
        "ru": "Устройства %s отключены.",
        "pt": "O dispositivo %s está desativado.",
        "nl": "Device %s is gehandicapt.",
        "fr": "Le dispositif %s est désactivé.",
        "it": "Il dispositivo %s è disattivato.",
        "es": "El dispositivo %s está deshabilitado.",
        "pl": "Device %s jest niepełnosprawne.",
        "uk": "Пристрої %s вимкнено.",
        "zh-cn": "Device %s残疾。."
    },
    "Language": {
        "en": "Language: %s",
        "de": "Sprache: %s",
        "ru": "Язык: %s",
        "pt": "Língua: %s",
        "nl": "Taal: %s",
        "fr": "Langue: %s",
        "it": "Lingua: %s",
        "es": "Idioma: %s",
        "pl": "Język: %s",
        "uk": "Мова: %s",
        "zh-cn": "语文: %s"
    },
    "DeviceID": {
        "en": "Device ID: %s",
        "de": "Geräte-ID: %s",
        "ru": "ID устройства: %s",
        "pt": "ID do dispositivo: %s",
        "nl": "Device ID: %s",
        "fr": "ID du dispositif: %s",
        "it": "ID dispositivo: %s",
        "es": "ID del dispositivo: %s",
        "pl": "Device ID: %s",
        "uk": "Ідентифікатор пристрою: %s",
        "zh-cn": "Device ID: %s"
    },
    "Please enter an IP": {
        "en": "Please enter an IP.",
        "de": "Bitte geben Sie eine IP ein.",
        "ru": "Пожалуйста, введите IP.",
        "pt": "Por favor, insira um IP.",
        "nl": "Betrek alsjeblieft een IP.",
        "fr": "Veuillez entrer une IP.",
        "it": "Si prega di inserire un IP.",
        "es": "Por favor, introduzca una IP.",
        "pl": "Wstęp do IP.",
        "uk": "Введіть номер мобільного, який Ви вказали при укладаннi договору з банком - для ідентифікації.",
        "zh-cn": "请加入IP。."
    },
    "Port default": {
        "en": "No Port specified! Port default set to 80.",
        "de": "Kein Port angegeben! Port Standard auf 80 gesetzt.",
        "ru": "Порт не указан! Порт по умолчанию установлен до 80.",
        "pt": "Nenhuma porta especificada! Porta padrão definido para 80.",
        "nl": "Geen Port gespecificeerd! Portafwijking gestart tot 80.",
        "fr": "Pas de port spécifié ! Port default set to 80.",
        "it": "Nessuna porta specificata! Impostazione predefinita della porta a 80.",
        "es": "¡No hay Puerto especificado! Port default set to 80.",
        "pl": "Port nie został określony. Port domyślny plan to 80 lat.",
        "uk": "Ні Порт вказаний! Портовий за замовчуванням встановлюється до 80.",
        "zh-cn": "无港口规定! 第80条."
    },
    "USED_Username": {
        "en": "Username and password are used for device %s.",
        "de": "Benutzername und Passwort werden für das Gerät %s verwendet.",
        "ru": "Имя пользователя и пароль используются для устройства %s.",
        "pt": "Nome de usuário e senha são usados para dispositivo %s.",
        "nl": "Noem en wachtwoord worden gebruikt voor apparaat %s.",
        "fr": "Nom d'utilisateur et mot de passe sont utilisés pour le dispositif %s.",
        "it": "Nome utente e password sono utilizzati per il dispositivo %s.",
        "es": "Nombre de usuario y contraseña se utilizan para el dispositivo %s.",
        "pl": "Użytkowniki i hasła są używane do urządzenia %s.",
        "uk": "Ім'я та пароль використовуються для пристрою %s.",
        "zh-cn": "用于装置%s。."
    },
    "Offline": {
        "en": "Device %s starts offline...",
        "de": "Gerät %s startet offline.",
        "ru": "Устройство %s начинает офлайн.",
        "pt": "O dispositivo %s começa offline.",
        "nl": "Device %s begint offline.",
        "fr": "L'appareil %s commence hors ligne.",
        "it": "Il dispositivo %s inizia offline.",
        "es": "El dispositivo %s comienza fuera de línea.",
        "pl": "Uwaga %s rozpoczyna się od linii.",
        "uk": "Пристрої %s стартують в автономному режимі.",
        "zh-cn": "%s名司机开除。."
    },
    "Standby_Modus": {
        "en": "The device %s starts in standby modus...",
        "de": "Das Gerät %s startet im Standby-Modus.",
        "ru": "Устройство %s начинается в режиме ожидания.",
        "pt": "O dispositivo %s começa no modus standby.",
        "nl": "Het apparaat %s begint in stand-by modus.",
        "fr": "L'appareil %s commence par modus standby.",
        "it": "Il dispositivo %s inizia in modalità standby.",
        "es": "El dispositivo %s comienza en modo de espera.",
        "pl": "Urządzenie %s rozpoczyna się w trybie standby.",
        "uk": "Пристрій %s починається в режимі очікування.",
        "zh-cn": "装置%s在待命单元中开始。."
    },
    "Unreachable": {
        "en": "Your device with IP %s:%s is unreachable. Please check your Instance configuration and restart your adapter.",
        "de": "Ihr Gerät mit IP %s:%s ist nicht erreichbar. Bitte überprüfen Sie Ihre Instanz-Konfiguration und starten Sie Ihren Adapter neu.",
        "ru": "Ваше устройство с IP %s:%s недоступно. Пожалуйста, проверьте настройки и перезагрузите адаптер.",
        "pt": "Seu dispositivo com IP %s:%s não é possível. Verifique sua configuração de instância e reinicie seu adaptador.",
        "nl": "Je apparaat met IP %s:%s is onbereikbaar. Controleer uw instance configuratie en herstel uw adapter.",
        "fr": "Votre appareil avec IP %s:%s est inaccessible. Veuillez vérifier la configuration de votre instance et redémarrer votre adaptateur.",
        "it": "Il tuo dispositivo con IP %s:%s è irraggiungibile. Si prega di controllare la configurazione del vostro caso e riavviare il vostro adattatore.",
        "es": "Su dispositivo con IP %s:%s es inalcanzable. Por favor, compruebe su configuración de Instance y reinicie su adaptador.",
        "pl": "Urządzenie z IP %s:%s nie jest dozwolone. Poświadczasz swoją konfigurację i odwracaj swojego adaptera.",
        "uk": "Ваш пристрій з IP %s:%s ненадійна. Будь ласка, перевірте налаштування та перезапустіть адаптер.",
        "zh-cn": "你有IP%s的装置:其%s是无法实现的。 请检查你的配置,并重新安排你们的适应者。."
    },
    "Connection": {
        "en": "Connection to %s device failed.",
        "de": "Verbindung zu %s Gerät gescheitert.",
        "ru": "Подключение к %s устройству не удалось.",
        "pt": "A conexão com %s dispositivo falhou.",
        "nl": "Verbinding met een apparaat faalde.",
        "fr": "La connexion à %s appareil a échoué.",
        "it": "La connessione a %s dispositivo non è riuscita.",
        "es": "La conexión a %s dispositivo falló.",
        "pl": "Połączenie do %s urządzenia nie powiodło się.",
        "uk": "Підключення до %s пристрою не вдалося.",
        "zh-cn": "对%s个装置的控制失败。."
    },
    "DEVICEINFO": {
        "en": "DEVICEINFO created for device %s.",
        "de": "DEVICEINFO erstellt für das Gerät %s.",
        "ru": "ДевайсИнфо создан для устройства %s.",
        "pt": "DESENVOLVIMENTO criado para o dispositivo %s.",
        "nl": "DEVICEINFO Gemaakt voor apparaat %s.",
        "fr": "DEVICEINFO créé pour le dispositif %s.",
        "it": "DISPONIBILE creato per dispositivo %s.",
        "es": "DEVICEINFO creado para el dispositivo %s.",
        "pl": "DEVICEN Zaprojektowany dla urządzenia %s.",
        "uk": "ДЕВИТІНФО створений для пристрою %s.",
        "zh-cn": "DEVICEINFO 制造装置%s。."
    },
    "Remote_Folder": {
        "en": "Remote Folder created for device %s.",
        "de": "Remote Folder erstellt für Gerät %s.",
        "ru": "Remote Folder создан для устройства %s.",
        "pt": "Pasta remota criada para dispositivo %s.",
        "nl": "Verwijder Folder gemaakt voor apparaat %s.",
        "fr": "Dossier distant créé pour le périphérique %s.",
        "it": "Cartella remota creata per il dispositivo %s.",
        "es": "Carpeta remota creada para el dispositivo %s.",
        "pl": "Remote Folder stworzył dla urządzenia %s.",
        "uk": "Віддалений складник, створений для пристрою %s.",
        "zh-cn": "用于装置第%s号的遥控器。."
    },
    "Determine": {
        "en": "Cannot determine the status of device %s.",
        "de": "Kann den Status des Geräts %s nicht bestimmen.",
        "ru": "Не можете определить статус устройства %s.",
        "pt": "Não é possível determinar o estado do dispositivo %s.",
        "nl": "Kan de status van apparaat %s niet bepalen.",
        "fr": "Ne peut pas déterminer l'état du dispositif %s.",
        "it": "Non è possibile determinare lo stato del dispositivo %s.",
        "es": "No se puede determinar el estado del dispositivo %s.",
        "pl": "Cannot określa status urządzenia %s.",
        "uk": "Не можна визначити стан пристрою %s.",
        "zh-cn": "评 注%s."
    },
    "TunerInfos": {
        "en": "TunerInfos created for device %s.",
        "de": "TunerInfos erstellt für Gerät %s.",
        "ru": "TunerInfos создан для устройства %s.",
        "pt": "TunerInfos criado para dispositivo %s.",
        "nl": "TunerInfos gemaakt voor apparaat %s.",
        "fr": "TunerInfos créées pour le dispositif %s.",
        "it": "TunerInfos creato per dispositivo %s.",
        "es": "TunerInfos creado para el dispositivo %s.",
        "pl": "TunerInfos stworzył dla urządzenia %s.",
        "uk": "TunerInfos створений для пристрою %s.",
        "zh-cn": "用于装置的图里信息系统 %s."
    },
    "StatusInfos": {
        "en": "StatusInfos created for device %s.",
        "de": "StatusInfos erstellt für Gerät %s.",
        "ru": "StatusInfos создан для устройства %s.",
        "pt": "StatusInfos criado para dispositivo %s.",
        "nl": "StatusInfos gemaakt voor apparaat %s.",
        "fr": "StatusInfos créées pour le périphérique %s.",
        "it": "StatusInfos creato per il dispositivo %s.",
        "es": "StatusInfos creado para el dispositivo %s.",
        "pl": "StatusInfos stworzył dla urządzenia %s.",
        "uk": "СтатусІнфос створений для пристрою %s.",
        "zh-cn": "用于装置的现况信息第%s号。."
    },
    "Cannot_Bouquets": {
        "en": "Cannot find any Bouquets from device %s.",
        "de": "Kann keine Bouquets vom Gerät %s finden.",
        "ru": "Не можете найти любые Букеты с устройства %s.",
        "pt": "Não é possível encontrar nenhum Bouquets do dispositivo %s.",
        "nl": "Kan geen Bouquets vinden van apparaat %s.",
        "fr": "Ne trouvez pas de Bouquets de l'appareil %s.",
        "it": "Non è possibile trovare alcun Bouquets dal dispositivo %s.",
        "es": "No se pueden encontrar Bouquets desde el dispositivo %s.",
        "pl": "Cannot odnalazł urządzenie %s.",
        "uk": "Не можна знайти будь-які Букети з пристрою %s.",
        "zh-cn": "未发现任何布克从装置第%s号。."
    },
    "Bouquets_and_EPG": {
        "en": "Bouquets and EPG created for device  %s.",
        "de": "Bouquets und EPG erstellt für Gerät %s.",
        "ru": "Букеты и EPG созданы для устройства %s.",
        "pt": "Bouquets e EPG criados para dispositivo %s.",
        "nl": "Bouquets en EPG gemaakt voor apparaat %s.",
        "fr": "Bouquets et EPG créés pour le dispositif %s.",
        "it": "Bouquets e EPG creati per il dispositivo %s.",
        "es": "Bouquets y EPG creados para el dispositivo %s.",
        "pl": "Bouquets and EPG – stworzone dla urządzenia %s.",
        "uk": "Букети і ЕПГ створюються для пристрою %s.",
        "zh-cn": "用于装置第%s号。."
    },
    "Starts_Interval": {
        "en": "Device %s starts with an interval of %s seconds.",
        "de": "Gerät %s beginnt mit einem Intervall von %s Sekunden.",
        "ru": "Устройство %s начинается с интервала %s секунд.",
        "pt": "O dispositivo %s começa com um intervalo de %s segundos.",
        "nl": "Device %s begint met een interval van %s seconden.",
        "fr": "Le périphérique %s commence par un intervalle de %s secondes.",
        "it": "Il dispositivo %s inizia con un intervallo di %s secondi.",
        "es": "El dispositivo %s comienza con un intervalo de %s segundos.",
        "pl": "Device %s rozpoczyna się od przedziału %s sekund.",
        "uk": "Пристрої %s починаються з інтервалом %s секунд.",
        "zh-cn": "%s 证人开始%s秒。."
    },
    "All_Datapoints": {
        "en": "All Datapoints: %s.",
        "de": "Alle Datapoints: %s.",
        "ru": "Все данные: %s.",
        "pt": "Todos os Datapoints: %s.",
        "nl": "Alle Datapoints: %s.",
        "fr": "Tous les points de données: %s.",
        "it": "Tutti i Datapoint: %s.",
        "es": "All Datapoints: %s.",
        "pl": "Wszystkie dane: %s.",
        "uk": "Усі точки даних: %s.",
        "zh-cn": "所有数据点:%s."
    },
    "Deleted": {
        "en": "Deleted: %s.",
        "de": "Gelöscht: %s.",
        "ru": "Удален: %s.",
        "pt": "Excluído: %s.",
        "nl": "Gewist: %s.",
        "fr": "Deleted: %s.",
        "it": "Cancellato: %s.",
        "es": "Suprimido: %s.",
        "pl": "W: %s.",
        "uk": "Видалення: %s.",
        "zh-cn": "删除:%s."
    },
    "Interval_Recording": {
        "en": "Interval Recording starts for %s.",
        "de": "Interval Recording beginnt für %s.",
        "ru": "Интервал запись начинается на %s.",
        "pt": "Registro de Intervalo começa para %s.",
        "nl": "Interval Recording begint voor %s.",
        "fr": "L'enregistrement intervale commence pour %s.",
        "it": "Interval Recording inizia per %s.",
        "es": "Interval Recording comienza por %s.",
        "pl": "Interval Recording rozpoczyna się od %s.",
        "uk": "Interval Запис починається на %s.",
        "zh-cn": "B. 汇率记录开始为%s个."
    },
    "Start_recording_interval": {
        "en": "Start recording interval for %s.",
        "de": "Aufnahmeintervall für %s starten.",
        "ru": "Запуск интервала записи для %s.",
        "pt": "Comece o intervalo de gravação para %s.",
        "nl": "Begin de interval op te nemen voor %s.",
        "fr": "Commencez l'intervalle d'enregistrement pour %s.",
        "it": "Avviare l'intervallo di registrazione per %s.",
        "es": "Comience el intervalo de grabación para %s.",
        "pl": "Odcinek %s.",
        "uk": "Почати інтервал запису для %s.",
        "zh-cn": "B. 开始记录%s年的间隔."
    },
    "Starting_checking_recordings": {
        "en": "Starting checking the recordings for device %s.",
        "de": "Beginn der Überprüfung der Aufnahmen für das Gerät %s.",
        "ru": "Начало проверки записей для устройства %s.",
        "pt": "Iniciando a verificação das gravações para o dispositivo %s.",
        "nl": "Begin de opnames te controleren voor apparaat %s.",
        "fr": "En commençant à vérifier les enregistrements du périphérique %s.",
        "it": "Controllo delle registrazioni per il dispositivo %s.",
        "es": "Comienza a revisar las grabaciones para el dispositivo %s.",
        "pl": "Zaczyna sprawdzać nagrania dla urządzenia %s.",
        "uk": "Почати перевірку записів для пристрою %s.",
        "zh-cn": "B. 开始检查装置的录音记录 %s."
    },
    "Checking_DeepStandby": {
        "en": "Checking DeepStandby from device %s.",
        "de": "Prüfen von DeepStandby vom Gerät %s.",
        "ru": "Проверка DeepStandby с устройства %s.",
        "pt": "Verificando DeepStandby do dispositivo %s.",
        "nl": "Controleer DeepStandby van apparaat %s.",
        "fr": "Vérification de DeepStandby depuis le périphérique %s.",
        "it": "Controllo DeepStandby dal dispositivo %s.",
        "es": "Revisando DeepStandby desde el dispositivo %s.",
        "pl": "Checking DeepStandby z urządzenia %s.",
        "uk": "Перевірити DeepStandby від пристрою %s.",
        "zh-cn": "B. 从装置中查验深装置 %s."
    },
    "Connected_device": {
        "en": "Connected with device %s.",
        "de": "Mit dem Gerät %s verbunden.",
        "ru": "Подключен с устройством %s.",
        "pt": "Conectado com dispositivo %s.",
        "nl": "Geconnecteerd met apparaat %s.",
        "fr": "Connecté avec le dispositif %s.",
        "it": "Collegato con dispositivo %s.",
        "es": "Conectado con el dispositivo %s.",
        "pl": "Połączenie z urządzeniem %s.",
        "uk": "З'єднання з пристроєм %s.",
        "zh-cn": "A. 与装置的接触 %s."
    },
    "Device_disconnected": {
        "en": "Device %s disconnected.",
        "de": "Gerät %s getrennt.",
        "ru": "Устройство %s отключено.",
        "pt": "Dispositivo %s desligado.",
        "nl": "Vernietiging %s.",
        "fr": "Appareil %s déconnecté.",
        "it": "Dispositivo %s scollegato.",
        "es": "Dispositivo %s desconectado.",
        "pl": "Zbiór %s.",
        "uk": "Пристрої %s відключені.",
        "zh-cn": "Device %s脱钩。."
    },
    "Device_offline": {
        "en": "Device %s is offline.",
        "de": "Gerät %s ist offline.",
        "ru": "Устройство %s оффлайн.",
        "pt": "O dispositivo %s está offline.",
        "nl": "Device %s is offline.",
        "fr": "L'appareil 1 est hors ligne.",
        "it": "Il dispositivo %s è offline.",
        "es": "El dispositivo %s está fuera de línea.",
        "pl": "Uwaga %s.",
        "uk": "Пристрої %s офлайн.",
        "zh-cn": "Device %s号不线。."
    },
    "reject_device": {
        "en": "reject: %s device: %s",
        "de": "Ablehnung: %s Gerät: %s",
        "ru": "отказ: %s устройство: %s",
        "pt": "rejeitar: %s dispositivo: %s",
        "nl": "afwijzing: %s apparaat: %s",
        "fr": "rejet: %s appareil: %s",
        "it": "rifiuto: %s dispositivo: %s",
        "es": "rechazar: %s dispositivo: %s",
        "pl": "odrzucenie: %s urządzenie: %s",
        "uk": "відхилення: %s пристрій: %s",
        "zh-cn": "反对:%s装置:%s"
    },
    "Used_HTTPS": {
        "en": "Used HTTPS for device %s.",
        "de": "Gebrauchte HTTPS für Gerät %s.",
        "ru": "Используется HTTPS для устройства %s.",
        "pt": "HTTPS usado para dispositivo %s.",
        "nl": "Gebruikte HTPS voor apparaat %s.",
        "fr": "HTTPS utilisé pour le périphérique %s.",
        "it": "HTTPS usato per il dispositivo %s.",
        "es": "HTTPS usado para el dispositivo %s.",
        "pl": "Zastosowanie protokołu %s.",
        "uk": "Використовується HTTPS для пристрою %s.",
        "zh-cn": "使用HTTPS进行装置%s."
    },
    "Start Update for device": {
        "en": "Start Update for device %s.",
        "de": "Start Update für das Gerät %s.",
        "ru": "Start Update для устройства %s.",
        "pt": "Iniciar atualização para dispositivo %s.",
        "nl": "Start Update voor apparaat %s.",
        "fr": "Mettre à jour le dispositif %s.",
        "it": "Avviare l'aggiornamento per il dispositivo %s.",
        "es": "Iniciar actualización para el dispositivo %s.",
        "pl": "Uruchomienie urządzenia %s.",
        "uk": "Почати оновлення для пристрою %s.",
        "zh-cn": "B. 装置的最新情况 %s."
    },
    "In process": {
        "en": "In process: %s",
        "de": "Im Prozess: %s",
        "ru": "В процессе: %s",
        "pt": "Em processo: %s",
        "nl": "In het proces: %s",
        "fr": "En cours: %s",
        "it": "In processo: %s",
        "es": "En proceso: %s",
        "pl": "Proces: %s",
        "uk": "В процесі: %s",
        "zh-cn": "进程: %s"
    },
    "INFO powerstate": {
        "en": "INFO powerstate: %s",
        "de": "INFO Powerstate: %s",
        "ru": "Powerstate ИНФО: %s",
        "pt": "INFO powerstate: %s",
        "nl": "INFO powerstate: %s",
        "fr": "INFO powerstate: %s",
        "it": "Stato di potere INFO: %s",
        "es": "INFO powerstate: %s",
        "pl": "INFO powerstate: %s",
        "uk": "ІНФО потужністьдержава: %s",
        "zh-cn": "电力公司: %s"
    },
    "Device_standby": {
        "en": "Device %s is in standby.",
        "de": "Das Gerät %s ist im Standby.",
        "ru": "Устройство %s находится в режиме ожидания.",
        "pt": "O dispositivo %s está em espera.",
        "nl": "Device %s is stand-by.",
        "fr": "L'appareil %s est en attente.",
        "it": "Il dispositivo %s è in standby.",
        "es": "El dispositivo %s está en espera.",
        "pl": "Uwaga %s znajduje się w rękach.",
        "uk": "Пристрої %s в режимі очікування.",
        "zh-cn": "%s人待命。."
    },
    "Device_online": {
        "en": "Device %s is online.",
        "de": "Gerät %s ist online.",
        "ru": "Устройство %s онлайн.",
        "pt": "O dispositivo %s está online.",
        "nl": "Device %s is online.",
        "fr": "L'appareil %s est en ligne.",
        "it": "Il dispositivo %s è online.",
        "es": "El dispositivo %s está en línea.",
        "pl": "Device %s jest online.",
        "uk": "Пристрої %s онлайн.",
        "zh-cn": "%s 证人在线。."
    },
    "New interval Online": {
        "en": "Device %s is online. New interval for device %s is set.",
        "de": "Gerät %s ist online. Ein neuer Intervall für das Gerät %s wird eingestellt.",
        "ru": "Устройство %s онлайн. Установлен новый интервал для устройства %s.",
        "pt": "O dispositivo %s está online. Novo intervalo para o dispositivo %s é definido.",
        "nl": "Device %s is online. Nieuwe interval voor apparaat %s is klaar.",
        "fr": "Appareil %s est en ligne. Un nouvel intervalle pour le dispositif %s est défini.",
        "it": "Il dispositivo %s è online. Viene impostato un nuovo intervallo per il dispositivo %s.",
        "es": "El dispositivo %s está en línea. Se establece un nuevo intervalo para el dispositivo %s.",
        "pl": "Device %s jest online. Uruchomiono nowe przedziały dla urządzenia %s.",
        "uk": "Пристрої %s онлайн. Новий інтервал для пристрою %s встановлюється.",
        "zh-cn": "Device %s 在线。 安装了用于装置%s的新间隔。."
    },
    "find_info_device": {
        "en": "Can't find any info from device %s.",
        "de": "Kann keine Informationen von device %s finden.",
        "ru": "Не можете найти информацию с устройства %s.",
        "pt": "Não consigo encontrar nenhuma informação do dispositivo %s.",
        "nl": "Ik kan geen informatie vinden van apparaat %s.",
        "fr": "On ne peut pas trouver d'info de l'appareil %s.",
        "it": "Non è possibile trovare informazioni da %s del dispositivo.",
        "es": "No se puede encontrar ninguna información de los %s del dispositivo.",
        "pl": "Nie można znaleźć żadnej informacji z urządzeń %s.",
        "uk": "Не знайти інформацію про пристрій %s.",
        "zh-cn": "坎特发现从装置中找到任何电缆 %s."
    },
    "getcurrent + tunerinfo": {
        "en": "getcurrent + tunerinfo: %s",
        "de": "getcurrent + tunerinfo: %s",
        "ru": "getcurrent + tunerinfo: %s",
        "pt": "getcurrent + tunerinfo: %s",
        "nl": "getcurrent + tunerinfo: %s",
        "fr": "getcurrent + tunerinfo: %s",
        "it": "getcurrent + tunerinfo: %s",
        "es": "getcurrent + tunerinfo: %s",
        "pl": "getcurrent + tunerinfo: %s",
        "uk": "getcurrent + tunerinfo: %s",
        "zh-cn": "getcurrent + tunerinfo: %s"
    },
    "Update deviceInfo": {
        "en": "Update deviceInfo %s.",
        "de": "Update deviceInfo %s.",
        "ru": "Обновление устройстваInfo %s.",
        "pt": "Dispositivo de atualizaçãoInfo %s.",
        "nl": "Update apparatuur %s.",
        "fr": "Update deviceInfo %s.",
        "it": "Aggiornare il dispositivoInfo %s.",
        "es": "Actualizar dispositivoInfo %s.",
        "pl": "Urządzenie Info %s.",
        "uk": "Оновлення пристроюInfo %s.",
        "zh-cn": "最新资料%s."
    },
    "Start Update deviceInfo": {
        "en": "Start Update deviceInfo %s.",
        "de": "Start Update deviceInfo %s.",
        "ru": "Начните обновление устройстваInfo %s.",
        "pt": "Iniciar dispositivo de atualizaçãoInfo %s.",
        "nl": "Start Update apparaat Info %s.",
        "fr": "Start Update deviceInfo %s.",
        "it": "Avviare il dispositivo di aggiornamentoInfo %s.",
        "es": "Start Update deviceInfo %s.",
        "pl": "Zastosowanie Info %s.",
        "uk": "Початок оновлення пристроюInfo %s.",
        "zh-cn": "B. 最新资料 %s."
    },
    "Request": {
        "en": "Request: %s",
        "de": "Anfrage: %s",
        "ru": "Запрос: %s",
        "pt": "Pedido: %s",
        "nl": "Verzoek: %s",
        "fr": "Demande: %s",
        "it": "Richiesta: %s",
        "es": "Solicitud: %s",
        "pl": "Request: %s",
        "uk": "Запит: %s",
        "zh-cn": "请求: %s"
    },
    "Response": {
        "en": "Response: %s",
        "de": "Antwort: %s",
        "ru": "Ответ: %s",
        "pt": "Resposta: %s",
        "nl": "Response: %s",
        "fr": "Réponse : %s",
        "it": "Risposta: %s",
        "es": "Respuesta: %s",
        "pl": "Response: %s",
        "uk": "Відповідь: %s",
        "zh-cn": "答复: %s"
    },
    "getRequest": {
        "en": "getRequest: %s",
        "de": "getRequest: %s",
        "ru": "getRequest: %s",
        "pt": "getRequest: %s",
        "nl": "getRequest: %s",
        "fr": "getRequest: %s",
        "it": "getRequest: %s",
        "es": "getRequest: %s",
        "pl": "getRequest: %s",
        "uk": "getRequest: %s",
        "zh-cn": "getRequest: %s"
    },
    "path": {
        "en": "Path: %s",
        "de": "Pfad: %s",
        "ru": "Путь: %s",
        "pt": "Caminho: %s",
        "nl": "Path:",
        "fr": "Sentier: %s",
        "it": "Percorso: %s",
        "es": "Sendero: %s",
        "pl": "Path: %s",
        "uk": "Шлях: %s",
        "zh-cn": "Path: %s"
    },
    "response sendCommand": {
        "en": "response sendCommand: %s",
        "de": "response sendCommand: %s",
        "ru": "response sendCommand: %s",
        "pt": "response sendCommand: %s",
        "nl": "response sendCommand: %s",
        "fr": "response sendCommand: %s",
        "it": "response sendCommand: %s",
        "es": "response sendCommand: %s",
        "pl": "response sendCommand: %s",
        "uk": "response sendCommand: %s",
        "zh-cn": "response sendCommand: %s"
    },
    "Command:": {
        "en": "Command: %s Device ID: %s",
        "de": "Befehl: %s Geräte-ID: %s",
        "ru": "Команда: %s ID устройства: %s",
        "pt": "Comando: %s ID do dispositivo: %s",
        "nl": "Commando: %s Device ID: %s",
        "fr": "Commandement: %s ID du dispositif: %s",
        "it": "Comando: %s ID dispositivo: %s",
        "es": "Comando: %s ID del dispositivo: %s",
        "pl": "Komenda: %s Device ID: %s",
        "uk": "Команда: %s Ідентифікатор пристрою: %s",
        "zh-cn": "指挥: %s 证人: %s"
    },
    "Receiver is Offline": {
        "en": "Receiver %s is Offline. Can't send a request!",
        "de": "Receiver %s ist Offline. Kann keine Anfrage senden!",
        "ru": "Приемник %s оффлайн. Не можете отправить заявку!",
        "pt": "Receiver %s está offline. Não posso enviar um pedido!",
        "nl": "Receiver %s is offline. Ik kan geen verzoek sturen!",
        "fr": "Le receveur %s est hors ligne. Je ne peux pas envoyer une demande !",
        "it": "Il ricevitore %s è offline. Non posso inviare una richiesta!",
        "es": "Receptor %s es Sin conexión. ¡No puedo enviar una petición!",
        "pl": "Receiver %s jest Offline. Nie może wysłać prośby!",
        "uk": "Приймач %s оффлайн. Не надішліть запит!",
        "zh-cn": "接受者%s人是线。 坎特发出请求!"
    },
    "Received unknown command": {
        "en": "Received unknown command %s for device %s",
        "de": "Unbekannter Befehl %s für Gerät %s empfangen",
        "ru": "Получена неизвестная команда %s для устройства %s",
        "pt": "Recebido comando desconhecido %s para dispositivo %s",
        "nl": "Onbekende commando %s voor apparaat %s",
        "fr": "Commande inconnue %s pour le dispositif %s",
        "it": "Ricevuto comando sconosciuto %s per dispositivo %s",
        "es": "Recibido comando desconocido %s para el dispositivo %s",
        "pl": "Nieznany dowódca %s dla urządzenia %s",
        "uk": "Надійшла невідома команда %s для пристрою %s",
        "zh-cn": "接收不明身份的车辆指挥 %s %s"
    },
    "Found file": {
        "en": "Found file %s",
        "de": "Gefundene Datei %s",
        "ru": "Найденный файл %s",
        "pt": "Arquivo encontrado %s",
        "nl": "Gevonden %s",
        "fr": "Trouvé fichier %s",
        "it": "Il file trovato %s",
        "es": "Archivo encontrado %s",
        "pl": "Plik %s",
        "uk": "Знайдено файл %s",
        "zh-cn": "档案 %s"
    },
    "File not found": {
        "en": "File not found: %s",
        "de": "Datei nicht gefunden: %s",
        "ru": "Файл не найден: %s",
        "pt": "Arquivo não encontrado: %s",
        "nl": "Geen bewijs gevonden: %s",
        "fr": "Fichier non trouvé: %s",
        "it": "File non trovato: %s",
        "es": "Archivo no encontrado: %s",
        "pl": "File nie odnaleziono: %s",
        "uk": "Файл не знайдено: %s",
        "zh-cn": "未发现: %s"
    },
    "Delete datapoint": {
        "en": "Delete datapoint %s",
        "de": "Löschen von Datenpunkt %s",
        "ru": "Удалить дата-точка %s",
        "pt": "Excluir datapoint %s",
        "nl": "Verwijder data %s",
        "fr": "Supprimer le point de données %s",
        "it": "Eliminare i dati %s",
        "es": "Eliminar el punto de datos %s",
        "pl": "Lista danych %s",
        "uk": "Видалення точок даних %s",
        "zh-cn": "删除数据点 %s"
    },
    "Filename not found": {
        "en": "Filename %s not found",
        "de": "Dateiname %s nicht gefunden",
        "ru": "Имя файла %s не найдено",
        "pt": "Nome do arquivo %s não encontrado",
        "nl": "Veldnaam %s niet gevonden.",
        "fr": "Nom de fichier %s non trouvé",
        "it": "Nome file %s non trovato",
        "es": "Nombre de archivo %s no encontrado",
        "pl": "Filename %s nie został znaleziony",
        "uk": "Ім'я файла %s не знайдено",
        "zh-cn": "第%s条"
    },
    "No filenames found in folder": {
        "en": "No filenames found in folder %s.",
        "de": "Keine Dateinamen im Ordner %s gefunden.",
        "ru": "Файлов не найдено в папке %s.",
        "pt": "Nenhum nome de arquivo encontrado na pasta %s.",
        "nl": "Geen dossiernamen gevonden in map %s.",
        "fr": "Aucun nom de fichier trouvé dans le dossier %s.",
        "it": "Nessun nome di file trovato nella cartella %s.",
        "es": "No se encontraron nombres de archivo en la carpeta %s.",
        "pl": "Nie ma nazwy plików w folderie %s.",
        "uk": "Не знайдено назв файлів в папці %s.",
        "zh-cn": "未发现的%s倍数。."
    },
    "Missing quality": {
        "en": "Missing quality %s.",
        "de": "Fehlende Qualität %s.",
        "ru": "Отсутствие качества %s.",
        "pt": "Qualidade de falta %s.",
        "nl": "Vermiste kwaliteit %s.",
        "fr": "La qualité manquante %s.",
        "it": "Qualità mancante %s.",
        "es": "Falta la calidad %s.",
        "pl": "Jakość %s.",
        "uk": "Якість промивання %s.",
        "zh-cn": "发布质量%s."
    },
    "Error": {
        "en": "Error %s - %s",
        "de": "Fehler %s - %s",
        "ru": "Ошибка %s - %s",
        "pt": "Erro %s - %s",
        "nl": "Error %s - %s",
        "fr": "Erreur %s - %s",
        "it": "Errore %s - %s",
        "es": "Error %s - %s",
        "pl": "Error %s - %s",
        "uk": "Про нас %s - %s",
        "zh-cn": "Error %s - %s"
    },
    "Folder": {
        "en": "Folder: %s",
        "de": "Ordner: %s",
        "ru": "Папка: %s",
        "pt": "Pasta: %s",
        "nl": "Folder: %s",
        "fr": "Folder: %s",
        "it": "Cartella: %s",
        "es": "Folder: %s",
        "pl": "Folder: %s",
        "uk": "Складv: %s",
        "zh-cn": "Folder: %s"
    },
    "Element": {
        "en": "Element: %s",
        "de": "Element: %s",
        "ru": "Элемент: %s",
        "pt": "Elemento: %s",
        "nl": "Element: %s",
        "fr": "Élément: %s",
        "it": "Elemento: %s",
        "es": "Elemento: %s",
        "pl": "Element: %s",
        "uk": "Навігація: %s",
        "zh-cn": "执行: %s"
    },
    "Change common": {
        "en": "Change common %s",
        "de": "Change common %s",
        "ru": "Change common %s",
        "pt": "Change common %s",
        "nl": "Change common %s",
        "fr": "Change common %s",
        "it": "Change common %s",
        "es": "Change common %s",
        "pl": "Change common %s",
        "uk": "Change common %s",
        "zh-cn": "Change common %s",
    }
};
